### ISSUE TITLE
Add geometry parser for XML-files [PYTHON]

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#1036]
The geometry.builder can be initialized using two x- and y-coordinates lists as follows 

```
    geo_builder = jps.GeometryBuilder()
    # CCW
    geo_builder.add_accessible_area([0, 0, 10, 0, 10, 10, 0, 10])
    geo_builder.add_accessible_area([10, 4, 20, 4, 20, 6, 10, 6])
```

Implement a python-parser to import old xml-geometries and extract these two lists.

**Comment by Ozaq** [comment]
@chraibi This is not possible to do automatically: 

The old geometry allowed for zero width walls, this is something we explicitly removed for the reimplementation. Adjacent polygons are always considered to be connected. Non crossable edges is currently not implemented and I would prefer to keep it this way.

I think we should rather semi-automatically convert all old geometries into something stupidly simple to parse and mixup those walls manually, e.g. redraw them with a 5cm wide wall for example.

Such a trivial json could be:

```json
{
  polygons: [
    {
      boundary: [
        {x: 0.0, y: 0.0 }, 
        ...
     ], 
     holes: [
       [
         {x: 1, y: 2},
         ...
       ]
     ]
}
```

Note: the above json is pretty much the shapely representation of a polygon with holes.

**Comment by Ozaq** [comment]
Closed after clarification with @chraibi
