### ISSUE TITLE
Sweeping for the Delaunay triangulation of this geometry fails

### ISSUE THREAD

**Issue by bcoueraud87** [JuPedSim/jpscore#1045]
**JuPedSim - JPScore**

- Current date   : 27/09/2022
- Version        : dev
- Compiler       : MSVC
- Commit hash    :
- Commit date    :
- Branch         : SUMO-integration
- Python         :

**Description of the bug**
The geometry is composed of two large rooms connected by a channel of width 3.5 meters. The GeometryBuilder fails with this error:

> Assertion failed: 0, file C:\Users\coue_be\Dev\vcpkg\buildtrees\poly2tri\src\bd85c3c204-6194be63e9.clean\poly2tri\sweep\sweep.cc, line 770

After consulting the source file above, the issue may be related to the orientation of the polygons.

**Expected behavior**
Apart from possible numerical issues linked to floating-point numbers, the sweeping algorithm should work: it works with widths of 3 meters and 4 meters but not 3.5.

**Additional context**
Here is the [geometry](https://github.com/JuPedSim/jpscore/files/9655124/geometry.txt) which can be visualized with this Python [script](https://github.com/JuPedSim/jpscore/files/9655149/vis.txt) (with the trajectory part to be commented out).

**Comment by Ozaq** [comment]
@bcoueraud87 Can you please retest this with the latest version on `SUMO-Integration`? I am unable to reproduce the observed behaviour with the geometry you provided.
