### ISSUE TITLE
ZeroDevisionError when Agent has no Orientation

### ISSUE THREAD

**Issue by ChristianHirt** [JuPedSim/jpscore#1057]
**JuPedSim - JPScore**

- Current date   : 10/02/2023
- Version        :
- Compiler       :
- Commit hash    :
- Commit date    :
- Branch         :  SUMO-Integration
- Python         :

**Describe the bug**
If an agent has an x- and y-orientation of 0 the simulation crashes while trying to calculate the orientation as degree of the agent.
This error appears repeatedly in simulations with multiple agents when an agent is pushed to the edge before a bottleneck. 
Examples are further below.

**Expected behavior**
This is a special case that needs to be handled separately because no degree can be calculated. However the simulation should not crash.

**Screenshots**
the exact traceback is : 
```
Traceback (most recent call last):
  File "/home/christian/jpscore/librarytest/w2_furter_back.py", line 117, in <module>
    main()
  File "/home/christian/jpscore/librarytest/w2_furter_back.py", line 109, in main
    writer.write_iteration_state(simulation)
  File "/home/christian/jpscore/python_modules/jupedsim/jupedsim/serialization.py", line 125, in write_iteration_state
    self._out.writelines(
  File "/home/christian/jpscore/python_modules/jupedsim/jupedsim/serialization.py", line 127, in <lambda>
    lambda agent: f"{agent.id}\t{self._frame}\t{agent.x}\t{agent.y}\t{0}\t{0.3}\t{0.3}\t{agent_orientaion_as_degrees(agent)}\t{0.4}\n",
  File "/home/christian/jpscore/python_modules/jupedsim/jupedsim/serialization.py", line 122, in agent_orientaion_as_degrees
    JpsCoreStyleTrajectoryWriter._normalize(vec2)
  File "/home/christian/jpscore/python_modules/jupedsim/jupedsim/serialization.py", line 145, in _normalize
    return (vec2[0] / len, vec2[1] / len)
ZeroDivisionError: float division by zero

```

the corresponding simulation and other examples can be found [here](https://github.com/JuPedSim/jpscore/files/10706648/examples.zip).
The simulations differ only in their way points. When reviewing the written simulations in jpsvis with enabled Agent Caption it can be seen that in the last frame only agents with numbers below 12 are still written into the trajectory. Agent 12 seems to cause the crash every time.

**Additional context**
the trajectories are created without the comment including the geometry path. i added this line in all trajectories in order to be displayed better in jpsvis.

**Comment by Ozaq** [comment]
@chraibi I would like to look into this with you next time I am in Jülich: Right now the Velocity Model is using the GenericAgents Data `orientation` field for its velocity vector. My intent was to make this `orientation` field to be always a unit vector and forbid the (0,0) vector. Reasoning here is that all agents always have an orientation.

The mistake here is that the Velocity model is still using the above mentioned field as velocity. But before I break the model subtly I would take a couple of minutes and look at this together with you.

**Comment by Ozaq** [comment]
@ChristianHirt This should be fixed now, can you recheck please recheck?
