### ISSUE TITLE
Convert BUW geometry to WKT

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#1091]
The attached old geomety file need to be converted to WKT (similar to #1071).

Please note that there is a buffer room around the building which is for the pathways (bounded by a fence and stairs, see [here](https://www.google.com/maps/place/Campus+Haspel/@51.2594173,7.1661973,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipNfk1jdzJHF_Q87QUL8KyriLOunUlRIye2dsm5U!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipNfk1jdzJHF_Q87QUL8KyriLOunUlRIye2dsm5U%3Dw114-h86-k-no!7i4032!8i3024!4m7!3m6!1s0x47b8d7cea24af533:0xc88532b74d8b0855!8m2!3d51.2594173!4d7.1661973!10e5!16s%2Fg%2F1td6x69x)).

[geometry_buffer.xml.zip](https://github.com/JuPedSim/jpscore/files/11272842/geometry_buffer.xml.zip)

**Comment by ChristianHirt** [comment]
![BUW](https://user-images.githubusercontent.com/92570899/233563974-00292e97-11ff-4599-8ab0-642e013fa46d.png)
plot of parsed geometry

![merged_buw](https://user-images.githubusercontent.com/92570899/233564073-9b9f348b-387f-46cf-bfd1-efa495f7850b.png)
plot of merged geometry

**Comment by Ozaq** [comment]
Done
