### ISSUE TITLE
Convert geometry of tests to WKT

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#1092]
The old geometries used in the [Jülich Tests](https://github.com/JuPedSim/jpscore/tree/master/systemtest/juelich_tests)  need to be converted to WKT (similar to https://github.com/JuPedSim/jpscore/issues/1071).

**Comment by ChristianHirt** [comment]
@JetteSchumann how wide should a wall be in the geometries of tests 11 and 12?
