### ISSUE TITLE
Which Router is functional?

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#141]
For refactoring the project we need to know which router are functioning and used. 

The following router are available. Which one is still functional?
* [x] `global_shortest`
   * OK. No errors. 
* [ ] `local_shortest`
   * not OK.  behaves like `global_shortest`
* [x] `quickest`
   * OK. Needs proper calibration. Parameters are hard coded    
* [x] `ff_global_shortest`
   * OK
* [ ] `ff_local_shortest`
   * Not OK. behaves like `global_shortest`
* [x] `ff_quickest`
   * OK (experimental, not calibrated, strangely synced agents)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:05

_Original comment by chraibi on 04 Nov 2015, 15:00_

---

@piccolodream maybe you can give us some update, so that we can work on this further.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 18, 2016, 08:55

@ArneGraf update this issue please.

**Comment by chraibi** [comment]
In Gitlab by @ArneGraf on Jan 4, 2017, 12:38

marked the task **`ff_quickest`** as incomplete

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 2, 2017, 10:11

assigned to @Erik-Andresen

**Comment by chraibi** [comment]
In Gitlab by @Erik-Andresen on Feb 2, 2017, 10:12

marked the task **`quickest`** as completed

**Comment by chraibi** [comment]
In Gitlab by @Erik-Andresen on Feb 2, 2017, 10:12

marked the task **`ff_quickest`** as completed

**Comment by chraibi** [comment]
In Gitlab by @Erik-Andresen on Feb 2, 2017, 10:12

marked the task **`ff_quickest`** as incomplete

**Comment by chraibi** [comment]
In Gitlab by @ArneGraf on Sep 4, 2017, 13:03

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Sep 6, 2017, 11:27

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Sep 6, 2017, 12:41

marked the task **`quickest`** as completed

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Sep 6, 2017, 12:58

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Sep 6, 2017, 13:04

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Sep 6, 2017, 13:07

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone

**Comment by zeroset** [comment]
see #618
