### ISSUE TITLE
Test and Fix Demo files 

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#161]
- [ ] Check all demo files
- [ ] Rename with counting with two digets, remove scenarion (e.g. XY_name, 01_corridor)

------
 - [ ] scenario_10_big_room
 - [ ] scenario_11_sources
 - [ ]  scenario_12_waiting_area
 - [ ]  scenario_13_schedule
 - [ ]  scenario_1_corridor
 - [ ]  scenario_2_bottleneck
 - [ ]  scenario_3_corner
 - [ ]  scenario_4_stairs
 - [ ]  scenario_5_events
 - [ ]  scenario_5_ship
 - [ ]  scenario_7_floorfield

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:06

_Original comment by b.schroeder on 04 Jan 2016, 09:27_

---

the following ini-File is not working:

[scenario_4_stairs-log_stairs.P0.dat](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/e70bfb81797a8d7c360c3d9e97907f02/scenario_4_stairs-log_stairs.P0.dat)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:06

_Original comment by b.schroeder on 11 Jan 2016, 11:40_

---

Shouldn't we remove the avi clips from the Rep?

./demos/scenario_1_corridor/demo_corridor.avi

./demos/scenario_2_bottleneck/demo_bottleneck.avi

./demos/scenario_3_corner/demo_corner.avi

./demos/scenario_4_stairs/subway_stairs.avi

./demos/scenario_5_events/events_information_sharing.avi

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:06

_Original comment by chraibi on 11 Jan 2016, 17:08_

---

Definitely. We have a YouTube-channel for that.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:06

_Original comment by chraibi on 11 Jan 2016, 19:34_

---

Benjamin could you please move all not working inifiles to a `tmp`-directory?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone

**Comment by schroedtert** [comment]
Will be continued in  #635.
