### ISSUE TITLE
LC grid is not 3D safe and ignores walls

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#178]
In 3D rooms pedestrians in different levels, which are obviously not neighbors will be recognized as such.

Example: Ped1 (0, 0, 10), ped2 (0, 1, 0) are considered by the LC-Algorithm as neighbors.
(but they are not).

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:06

_Original comment by chraibi on 21 Jan 2016, 23:13_

---

Title changed from **LC ist** to **LC is 2D!!**

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone

**Comment by zeroset** [comment]
@chraibi Does this issue still exist?

**Comment by chraibi** [comment]
Yes, I suppose so.

**Comment by zeroset** [comment]
@chraibi can you please evaluate if the bug still exists.

**Comment by schroedtert** [comment]
From the source code this bug still exists, and also peds in neighbouring rooms with a wall between will be treated as neighbours and have an influence.

**Comment by Ozaq** [comment]
LCGrid has been removed in favour of a 2D only implementation. I will close this issue therefore.
