### ISSUE TITLE
GOALS are not 3d proof

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#197]
In Gitlab by @chraibi on Mar 8, 2016, 09:39 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/183)]

goals are defined without a z-coordinate.

As long as they are outside, we can assume, they are well-defined. Are goals allowed to be inside a building? (I think, they are. At least the program checks, if a pedestrian reached its goal even if he is inside.)

If so, we need to talk about that.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:08

_Original comment by chraibi on 08 Mar 2016, 10:47_

---

This can be confusing. `Goals` are the ultimate target outside the building. At least as I understand it.

**Comment by schroedtert** [comment]
Goals are not 3d proof at the moment. They should not be placed inside a building, one can use `WaitingArea` instead. Since Routers are only considering the nearest door to a goal, this might cause unwanted route choices.

**Comment by schroedtert** [comment]
@chraibi can this be closed?

**Comment by chraibi** [comment]
Yes.
