### ISSUE TITLE
f.mack's legacy

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#233]
In Gitlab by @chraibi on Oct 7, 2016, 14:53 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/220)]

I have to geometry files I would like to share with you. You can use them for your own private testing or add them to the official tests.

"Equal distance" is a symmetric building. The two pedestrians (one commented out) should need the same time. I had some issue where this was not the case (one took the longer way).

"U shape" was to test the router (regarding the door hopping). The pedestrian should walk through the room and go back to the corridor (that is shorter than staying in the corridor).

Mohcine wants to make my report available to all of you. It contains some more documentation about the changes I made.

My branch parallel_ff will hopefully be merged soon into develop. Remember that it fixes the issues 213, 214, 215, and 218, so close them after merging.

[geometry_files.zip](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/1dba1bff12e2ed06a51ac70ac9e2d2b2/geometry_files.zip)

**Comment by zeroset** [comment]
@chraibi the file does not exist anymore. Do you have those geometries around somewhere? Otherwise, can we close this?
