### ISSUE TITLE
OpenMP + VS: compilation issues

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#236]
In Gitlab by @chraibi on Oct 27, 2016, 05:13 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/223)]

![image](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/29a22382295a0ded6dec0133b37541a4/image.png)

Can I just using "int" instead "size_t", I got that the VS2013 only support the OpenMP 2.0, and the OpenMP 2.0 doesn't allow the unsigned int in sentence "for".

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:10

closed

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 12:10

_Original comment by chraibi on 27 Oct 2016, 10:55_

---

You can do it if it helps.
However please make the change in a different branch than develop.

**Comment by schroedtert** [comment]
We still have this issue. Do we want to support the outdated OpenMP version? Or do we want all Windows developer to install a different compiler? If we decide so, we should require a specific OpenMP version in our CMake.

**Comment by Ozaq** [comment]
> We still have this issue. Do we want to support the outdated OpenMP version? Or do we want all Windows developer to install a different compiler? If we decide so, we should require a specific OpenMP version in our CMake.

Hmm requiring gcc or clang on windows opens a whole other can of worms...

**Comment by zeroset** [comment]
We don't support OpenMP 2.0, so we disabled OpenMP when using MSVC.
