### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#244]
In Gitlab by @chraibi on Dec 19, 2016, 16:43 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/231)]

## What should be done 

Clean up unused branches

## Why?

Too much unused branches is not good. For clarity and in order to not delete functionality we need to **cleanup**

**Comment by chraibi** [comment]
In Gitlab by @ArneGraf on Jan 4, 2017, 12:32

deleted 2 branches

**Comment by chraibi** [comment]
In Gitlab by @ArneGraf on Aug 2, 2017, 15:15

deleted 4 branches

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone

**Comment by Ozaq** [comment]
@chraibi these are the stale branches: https://github.com/JuPedSim/jpscore/branches/stale I would like to delete them all, ok? Then we can close this issue

**Comment by chraibi** [comment]
you can delete them all.

**Comment by Ozaq** [comment]
Done
