### ISSUE TITLE
osm-convert: creating geometries from open data

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#272]
In Gitlab by @bsmoehring on Jan 17, 2018, 19:12 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/261)]

## Short description of suggestion
Hello, I am currently developing a tool to convert openstreetmap data into jps-readable geometry.xml files.
You can check out the current version of my python code from https://github.com/bsmoehring/jpsTools

To be honest the code might still be unhandy for someone who didn't write it. But I provided some example datasets in https://github.com/bsmoehring/jpsTools/tree/master/jpsTools/osmImport/resources 

## Why would the enhancement be useful to most users
I believe that the power of jps will be accessible for way more users as soon as required data such as the geometry file can be easily converted from third party data sources. In addition the JOSM-Editor, which I find quite useful, provides well maintained and user-friendly editing tools based on vertices, just like jps. 

If anyone is interested in what I#m doing, fell free to contact me. I'd be honored if it might someday help some users creating geometry files. Since my usecase are train stations, the code and especially the input parameters are very likely not well supporting other areas for now. If you're facing problems, let me know.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jan 18, 2018, 13:09

cool idea. I'll have a look.

**Comment by zeroset** [comment]
@chraibi can we close this?

**Comment by chraibi** [comment]
We can reopen this when we have resources and need to work on it.
