### ISSUE TITLE
CMAKE Flags

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#284]
In Gitlab by @chraibi on Jun 4, 2018, 13:01 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/276)]

The compiler flags are a mess.

 The CMakeFileLists.txt needs some refactoring

- [ ] [For Visual Studio](https://stackoverflow.com/questions/45995784/how-to-set-compiler-options-with-cmake-in-visual-studio-2017)
- [ ] [using add_compiler_option](https://stackoverflow.com/questions/45955272/modern-way-to-set-compiler-flags-in-cross-platform-cmake-project)
- [ ] [VS_STARTUP_PROJECT](https://cmake.org/cmake/help/v3.6/prop_dir/VS_STARTUP_PROJECT.html)

**Comment by Ozaq** [comment]
@chraibi I think this can be closed unless there is still stuff missing. If so could you add the missing things here so that I can resolve them? Cheers!
