### ISSUE TITLE
Restarting a simulation

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#301]
In Gitlab by @anna-braun on Dec 7, 2018, 17:56 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/301)]

It could be necessary to restart/continue a simulation after it has been finished or canceled.  
Here is a idea which parameters are needed to restart the simulation:
*  group id
*  agent id
*  location x, y, z
*  velocity vx, vy 
*  frequency (source)
*  last frame = start frame
There can be a new trajectory file or the old one can be continued (maybe better).

**Comment by anna-braun** [comment]
@chraibi @schroedtert 
As we want to compute on Jureca, where we have a defined time slot we need to be able to stop and restart the simulations.

**Comment by anna-braun** [comment]
I startet a simulation for KapaKrit last Friday (19980 agents). After the time limit of 6 hours, 26 seconds were simulated (from 3000).
