### ISSUE TITLE
Error in sources (when using overlapping sources)

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#303]
## Summary
When using overlapping sources in larger geometries the program fails with a Segmentation fault in the VelocityModel when accessing the position of the neighbors.

## Inifile + Geometry file to reproduce bug
[Personen_ini.xml](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/uploads/a92b2f4f9efcd5e5af081dd82a0ba96f/Personen_ini.xml)

[Bahnsteige.xml](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/uploads/8a9c8bfc24ae68bf3d264379216a6129/Bahnsteige.xml)

**Comment by anna-braun** [comment]
@chraibi 
The Error changed, it's not a segmentation fault any longer:
![Bildschirmfoto 2019-12-20 um 14 30 24](https://user-images.githubusercontent.com/38530070/72244883-800ccd80-35ef-11ea-808e-23555efb69dd.png)
We do not really know if it is a problem of overlapping sources, as the problem also occurs for single sources. Here are the data which create the current error.
[test-wh-20200113.zip](https://github.com/JuPedSim/jpscore/files/4052810/test-wh-20200113.zip)

**Comment by chraibi** [comment]
Ok, the first question for me is it a source problem at all?

removing the sources gives me the following errors
```
[2020-01-14 21:43:30.153] [error] in AddTarget: calling FinalizeTargetLine
```

**Comment by anna-braun** [comment]
@chraibi I have this error, too (master branch, today 09:30h). I guess this is the floor field router problem from PR #623 (@schroedtert ?).     
When I do the simulation without sources, I have this error as well, but the simulation does not crash as it happens when using one or more sources, so it seems to be a problem of the sources.

**Comment by schroedtert** [comment]
No this is not the FF problem, this is solved with #623. This is the error, that the sources created pedestrians at (0,0) and this point is not inside the room.

**Comment by schroedtert** [comment]
Just a question, do source have the possibility to be distributed in a specific room? I couldn't find this parameter in the documentation.

`<group group_id="901" agent_parameter_id="1" room_id="0" subroom_id="1" number="1" goal_id="901" router_id="1"  />`

**Comment by anna-braun** [comment]
@schroedtert The (sub)room is defined in the group as you show it in the example.    
In the sources you can only give a start position, the (sub)room is taken from the group.
`<source id="901" caption="source_1-gl_9" group_id="901" time_min="0" time_max="6000" frequency="10" N_create="1" agents_max="40" x_min="93" x_max="97" y_min="0" y_max="5" greedy="true"/>`

**Comment by schroedtert** [comment]
Sorry, my bad, looked in the wrong file.

**Comment by schroedtert** [comment]
https://github.com/JuPedSim/jpscore/blob/ba513cbabf4be5153d18cc6c75e4c9dfcac17e08/libcore/src/pedestrian/AgentsSource.cpp#L220-L251

emptyPositions is never set, hence the pedestrians are always created at (0,0). The check if the point is inside the geometry is only done in the FF Router, resulting in the assert error.
I changed the demo by shifting it 5m to the right (x = x + 5) and using the FF Router gives the same error. 
[demo-sources-shifted.zip](https://github.com/JuPedSim/jpscore/files/4070642/demo-sources-shifted.zip)
