### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#310]
In Gitlab by @schroedtert on May 6, 2019, 09:44 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/317)]

Issue for collecting ideas for logging libraries

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 10, 2019, 15:35

In my opinion, it should be
- a header only library
- works throughout all files and write logs in a file

An example: 

https://github.com/gabime/spdlog

**Comment by zeroset** [comment]
We use SPDLog.
