### ISSUE TITLE
malloc_error_break

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#311]
In Gitlab by @anna-braun on May 11, 2019, 18:02 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/319)]

The error of issue #316 is gone, but there is another error, now...

![Bildschirmfoto_2019-05-11_um_17.39.04](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/a715b6ac39de47efd527de0aaef42db4/Bildschirmfoto_2019-05-11_um_17.39.04.png)

[correct_Bahnsteige.xml](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/uploads/bfb68e52ecd861ba2ea16efd02a2e33b/correct_Bahnsteige.xml)

[log-goal.txt](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/uploads/2e71bfd86980ea60c03f89cda3d96d45/log-goal.txt)

[Personen_ini.xml](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/uploads/26c7559ed1e1b4e2695fcad5685ec12b/Personen_ini.xml)

I do another simulation to see if the error occurs again.

For the small setup (Aufgabe6 - #316) there is no problem anymore.

**Comment by Ozaq** [comment]
@anna-braun @chraibi  I would like to look into this one, did this happen since again since you reported the issue? Can you upload the files to github? Looks like the links broke when exporting from gitlab.

**Comment by chraibi** [comment]
@Ozaq I updated the links
@anna-braun can you still reproduce this bug?

**Comment by anna-braun** [comment]
@chraibi @Ozaq 
I did not have this bug since I reported the issue, but I will test if it still occurs.

**Comment by orth-tim** [comment]
I had a malloc_error a few days ago: 
![error](https://user-images.githubusercontent.com/51954394/62211233-41b38700-b39e-11e9-963b-456ebc10d0f6.png)
 
Here is the folder with the [files](https://1drv.ms/u/s!AsV6LgpLPxYhgdNY_MrjJlqyIuMOwg?e=U5eebB).
The simulation is working with goal id ="10101" (not used in the simulation). The error only occurs after deleting this goal, deleting all other not used goals has no effect. Both cases are in the folder.

**Comment by chraibi** [comment]
@orth-tim could you please post information about your jpscore version?

maybe first run cmake, then make and post the output of jpscore.

**Comment by orth-tim** [comment]
I hope this ist helping:
<img width="558" alt="jpscore" src="https://user-images.githubusercontent.com/51954394/62214312-16806600-b3a5-11e9-9372-6c9954f3a815.png">

**Comment by Ozaq** [comment]
@orth-tim thanks I think I can start investigating with this. If I need more info Ill post it in this issue.

**Comment by Ozaq** [comment]
I have encountered several issues:
*  I cannot find the version info @orth-tim provided (g94a8e0ee) in the main git or any fork, neither the `kapakrit-anna` branch
* With current develop I cannot reproduce the error. I tried the `working` and `non_working` examples @orth-tim provided and tried to modify the working one by removing goal 10101. All run to completion.
* I tried to run `Personen_settings.xml` but this one does not even start on develop. The initialization fails with "could not distribute pedestrians"
```cpp
// from Building.cpp
if (!pedDistributor.Distribute(this)) {
      Log->Write("ERROR:\tcould not distribute the pedestrians\n");
      exit(EXIT_FAILURE);
 }
```

Since I see a memory leak issue with Goals and the bug description mentions that this is connected to having/not having goals in the settings I think those are connected. Looking at the data structures its unclear which part of the code is supposed to be "owning" Goals objects.

Could it maybe be that the `kappakrit-anna` branch has not been pushed to a remote? I would need the exact version of the code to track this down.

@chraibi what about your example not working? I assume this should work right?

**Comment by chraibi** [comment]
@orth-tim  your code is very old. Please update.
@ozak: I can check this tomorrow. You've got a log-file from the simulation saying why it does not distribute agents?

**Comment by Ozaq** [comment]
> @ozak: I can check this tomorrow. You've got a log-file from the simulation saying why it does not distribute agents?

Eh yes ofc... should have added that directly:
```
	...Done
ERROR: 	Cannot distribute 40 agents in Room 1000 . Maximum allowed: 16

ERROR:	could not distribute the pedestrians
```

**Comment by chraibi** [comment]
@ozak then you are lucky. It can not distribute 40 when there is only room for 16 :-)
 I remember @xuqiancheng did some little change lately. Could be the grid is too big?

But now, I just tested the `not_working` case and found something very disturbing. 

![Screenshot 2019-08-01 22 02 32](https://user-images.githubusercontent.com/5772973/62299882-685de480-b4a8-11e9-943d-6b396d62b1b2.png)


Probably related to #448

**Comment by Ozaq** [comment]
@chraibi This is strange, the not working case produced this for me:
```
 kkratz@kkratz-linux  /mnt/fast/jpsc-build/malloc_error/not_working  tree                 
.
├── Bahnsteig_Desiro_HC.xml
├── events.xml
├── flow_exit_id_2105_rate_1.75.txt
├── goal.vtk
├── log.txt
├── malloc_error.png
├── Personen_ini_Desiro_HC.xml
└── Traj.xml
```

**Comment by chraibi** [comment]
I think `fs::boost` and `fs::std` are behaving differently. To be continued in #448

**Comment by xuqiancheng** [comment]
@chraibi @Ozaq 
If you work in develop branch, the grid size depends on the size of agents. And we have to leave enough space between agents and walls. 
In Personen_ini.xml. model 4 is used, and radius of agents is 0.4 (too big?). 
I think we may need to reduce the size of agents.

**Comment by chraibi** [comment]
@anna-braun do you still encounter a problem? If yes, reopen, please.
