### ISSUE TITLE
Elevators

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#312]
In Gitlab by @anna-braun on May 20, 2019, 12:14 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/321)]

We have stairs and escalators, but we should also have elevators.

**Comment by chraibi** [comment]
How would you make a difference between escalators and elevators?
@anna-braun

**Comment by anna-braun** [comment]
Escalators are like stairs and can always be used. Elevators can only be used by a small number of people at the same time (number must be defined individually). And there is a time gap between entering and leaving the escalator (e.g. 10 seconds).

**Comment by zeroset** [comment]
Do we currently need this feature? I would like to close the issue and create a new one when we need Elevators.

**Comment by anna-braun** [comment]
yes we need it for KapaKrit
