### ISSUE TITLE
FF-Router for trains

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#313]
In Gitlab by @anna-braun on Jun 12, 2019, 15:52 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/323)]

The router ff_global_shortest_trips needs to be able to use the dynamic trains from #300.

**Comment by chraibi** [comment]
@schroedtert please small update here. Thanks!

**Comment by schroedtert** [comment]
Have not started on this one. Should the global router also be able to deal with this? 
Remark: Changed the title, since ff_global_shortest_trips will be removed.

**Comment by anna-braun** [comment]
I guess it's good if all routers can deal with it, but ff its most important.

**Comment by schroedtert** [comment]
Closed with #740 for FF router
