### ISSUE TITLE
Bug in track for trains

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#316]
In Gitlab by @123morgoth123 on Jun 19, 2019, 08:04 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/328)]

## Question 
I need some support with the tracks for trains feature. 

I changed the class of the subroom to „Platform“ and set the type of the wall of the track to „track-1“ in the geometry.

 Defined the start and end of the track in train_time_table.xml with the coordinates of the „track-1“-wall.

```
Terminal message: Arrival: 
TRAIN Desiro_HC at time: 30
enter with train Desiro_HC 
Enter correctGeometry: Building Has 5 Transitions 
room: 101 subroom_id 1 
Error in GetIntersection. Should be 2 but got 1
```

1. Which element should have 2 intersections? The „track-1“-wall and the ttt track are from intersection 10/130 to 10/20. I think I’m missing something. 

2. In addition: Can the track only be in/at one subroom? Because I get an error if the defined track in ttt uses more then one. 

```
Error: Arrival: TRAIN Desiro_HC at time: 30 could not find any track! Exit.
```
Folder witch data for the main question: [files](https://1drv.ms/u/s!AsV6LgpLPxYhgbIanMfhzZ8QJLIXuw?e=tQSaw4)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 10:16

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 10:16

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 10:17

assigned to @chraibi

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 10:38

Tim,

1. The track is from [20, 130]. But the Train  has following doors

```
<vertex px="0" py="7.76471"/>
<vertex px="0" py="9.16471"/>
```
and
```
<vertex px="0" py="18.66571"/>
<vertex px="0" py="20.06571"/>
```

Both don't "project" on the track, right?

2. Yes, one track. one subroom.

You can also have a look at the documentation [here](http://www.jupedsim.org/jpscore/2019-06-19-trains.html#train-timetable)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 11:19

changed the description

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 19, 2019, 15:39

The track starts by py=130 and ends by py=20. You are correct. py of the doors has to be negative so that they (should) "project" on the track.

I updated the files.

There is no more error while simulating but in jpsvis no train arrives and the peds are showing no response. They just move to one corner and stay there. I am sorry, I do not find the mistake.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 15:41

Can you upload the new files?

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 19, 2019, 15:44

They are already in the folder of the original post.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 19, 2019, 20:30

Thank you Tim for testing. 

`jpsvis` visualizes trains only when trajectories are in txt-format. 
So, in the inifile you gonna use `format="plain"` and rename the trajectory to a txt-file. See also [documentation](http://www.jupedsim.org/jpscore/2016-11-01-inifile#header) 

I' m still not sure if your train config is correct. 
Here you can find a [python-script](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/d0988afdaf0b50338e196ad7ac48d731/plot.py) to check by yourself. 

> usage: python plot.py Desiro_HC_ini.xml

These are the results: 
![img](https://www.dropbox.com/s/88y66nr2zotebfy/Screenshot%202019-06-19%2020.22.59.png?dl=1)

and here is the plot
![plot](/uploads/a4a0dac9f6690298ad9c9bdad6c68bd9/trains.png)

Maybe I'm not getting the write files and maybe there is a bug in `jpscore`. 

But before we dive in the code of `jpscore`, let's make sure the the files are correct.

Can you check again?

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 20, 2019, 07:40

Good morning @chraibi 

I have an idea: (edit: it seems to be a problem of the equation in the python script not in jpscore)

the documentation for the coordinates of the train's doors says:

>A(global)=track_start+train_start+A(local)

what it does:

>A(global)=track_start(global)+train_start(global)+A(local)

in my case that for the x-coordinate: A(global)=10+9.5+0=19.5  (like in the screenshot you did)

what it should be:

>A(global)=track_start(global)+train_start(local)+A(local)

that would be for the x-coordinate: A(global)=10-0.5+0=9.5

and that is the global x-coordinate I'm trying to get.


I made a test (it is in the folder of the original post as equation_test)

I adjusted the doors to the "what it does" equation. Now the door are set correctly according to python:
![equation_test](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/dcca14ff035efffdf98e7eaf1a81b202/equation_test.png)![trains](/uploads/9a72bd69186b8e4235fb80afbdceb668/trains.png)

but the simulation does not work:

```
Arrival: TRAIN Desiro_HC at time: 30
enter with train Desiro_HC 
Enter correctGeometry: Building Has 3 Transitions 
room: 101 subroom_id 1 
Error in GetIntersection. Should be 2 but got 0
``` 

and the train in jpsvis is a mess:
![train](/uploads/c0d64664055b59443478bc20bb322f42/train.png)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 20, 2019, 10:22

The new script for checking the trains is [here]([plot2.py](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/5e1cf25b13cea3e1392891c766d00ee5/plot2.py))

However, there is a bug in the code while splitting the walls.

**Comment by schroedtert** [comment]
Closed as we changed the train interface
