### ISSUE TITLE
Stair in the middle of a (sub)room -> hole for stairs

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#363]
In Gitlab by @anna-braun on Oct 2, 2018, 16:36 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/283)]

Defining a (sub)room or a hole in the middle of an other (sub)room for a stair, without subdividing the second (sub)room in more (sub)rooms.

![Grundriss+Treppe](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/58e4fa02fb331410c991954851531040/Grundriss+Treppe.png)

![Schnitt_Treppe](/uploads/54fccbe897a47b57bee9cd46613ad004/Schnitt_Treppe.png)

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on May 10, 2019, 15:27

Is there something new here?
It would be nice to use this for the KapaKrit geometry.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 10, 2019, 20:11

assigned to @sainho93

**Comment by anna-braun** [comment]
@schroedtert here are some examples for a stair in the middle of a room.
The first contains the "hole" in the room as additional walls. The other two examples have a subroom for the holes with crossings to the room. This subrooms could be signed as "holes" or similar.

[Stair_in_room.xml.txt](https://github.com/JuPedSim/jpscore/files/3466743/Stair_in_room.xml.txt)
[Stair_in_room_2.xml.txt](https://github.com/JuPedSim/jpscore/files/3466761/Stair_in_room_2.xml.txt)
[Stair_in_room_3.xml.txt](https://github.com/JuPedSim/jpscore/files/3466762/Stair_in_room_3.xml.txt)
