### ISSUE TITLE
Waiting areas

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#365]
In Gitlab by @anna-braun on Oct 4, 2018, 09:40 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/287)]

In order to simulate the transition from a platform edge to a train, waiting areas should be defined in front of the doors (transitions), for example, areas where only a certain number of people can stand.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Oct 9, 2018, 22:01

assigned to @chraibi

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Oct 9, 2018, 22:01

assigned to @schroedtert and unassigned @chraibi

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jan 28, 2019, 16:15

Any updates here?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Mar 15, 2019, 16:12

Should this be closed?

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Mar 21, 2019, 11:26

No it can not be closed. The distribution inside the waiting area needs to be adjusted be more realistic.

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on May 6, 2019, 19:12

I made some tests with a simple geometry to get to know waiting areas. Two issues occurred:
1. max_peds is ignored. In both cases (global_timer=”true” and “false”) more then the maximum amount of pedestrians are simultaneously in the waiting area
2. with global_timer=”false” two pedestrians are stuck in a waiting area

This folder contains the ini, geo and trajectory files: [(https://1drv.ms/f/s!AsV6LgpLPxYhgaMdAcUFsc6d6H5IPw) ]

**Comment by chraibi** [comment]
In Gitlab by @chraibi on May 11, 2019, 00:39

Hi Tim, 
@123morgoth123 

thanks for your comment. 

This feature is still WIP. 

For the second case, it seems that agents 36 and 13 are heading in the wrong direction

![Screenshot_2019-05-11_at_00.37.33](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/f4fbca492d06fee19837f65e7cdafe57/Screenshot_2019-05-11_at_00.37.33.png)

![Screenshot_2019-05-11_at_00.37.47](/uploads/159c0cdb63d2c9a66c03c42c3d3421fa/Screenshot_2019-05-11_at_00.37.47.png)

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on May 11, 2019, 11:49

Hi Tim,

1. Since the feature is WIP, we defined that max_ped should not be exceeded by the number of pedestrians heading for the first WA. Additionally, max_ped(WA1) <= max_ped(WA2).
2. When global timer "false" the pedestrians are stuck because in the last WA max_ped is reached, hence the WA is closed for all previous WAs. The other peds have already left the wa the remaining are not send to a closed WA. That's the reason for max_ped(WA1) <= max_ped(WA2). And since min_ped of WA2 is not reached, the counter will not start again. 

Hope the explanation helps, otherwise feel free to ask more questions! And thanks for testing and reporting your issues.

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 6, 2019, 10:07

Hello,
I think some issues occurred by others tests.

Issue: “overlapping” WAs

Two WAs (111 and 1119) are on different levels but 1119 is partly above 111. So, they “overlap”. 111 distributes pedestrians to 1119 and other WAs. Pedestrian 72 is sent from WA 01 to 111 and then to 1119 but stays in the “overlapping area” on the lower level until the waiting_time of 1119 is reached (155 sec). Then ped 72 walks to the specific goal (10119) on the upper level given by WA 1119. 
I tested different seeds and the issue did not occurred when no ped who is sent from 111 to 1119 reaches 111 in the “overlapping area”.

Issue: not getting next WA?

Another strange behaviour occurred on the stairs. Pedestrians reached the WAs (111 and 112) at the beginning of the stairs and should have got their next WA. When the waiting_time is reached (35 sec) they seemed to be pushed up the stairs by the other peds but they want to reach the WA at the beginning of the stairs again. They act normal after reaching 111 or 112 again. For WA 111 the peds are 43, 46 and 62, for WA 112 the peds are 5, 19, 27 and 103.

The folder contains the data of the test with the problems: [https://1drv.ms/u/s!AsV6LgpLPxYhgatD1DUIPkuTs8YReQ?e=MiSDLY]

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Jun 12, 2019, 11:05

@schroedtert Do you have any ideas for the issues of Tim?

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Jun 12, 2019, 14:59

Sorry @123morgoth123 for the late reply. If it takes longer till I reply, please remind me.

Issue: “overlapping” WAs:
Thanks for for finding out. This issue should be solved in 34e8fd3a. Could you please test?

Issue: not getting next WA?
It’s a known issue. I will need to find a good solution to handle this.

And if you find any other issue please report them as well! Thanks

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 13, 2019, 09:51

Hello @schroedtert, thanks for the response. Unfortunately nothing is changed, ped 72 is still waiting in the overlapping area in the tunnel. I hope I did erverything correct with the provided files. I downloaded them, adjusted the names (e.g. geometry_Goal.cpp to Goal.cpp) and replaced the old files with the new ones in the jpscore folder.

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Jun 13, 2019, 09:59

I think the easiest way, to make sure you get the correct version of each files is to use git. Did you recompile jpscore after you changed the files? @123morgoth123

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2019, 11:08

Maybe you could show us a screenshot like this one

![](https://www.dropbox.com/s/55st35gmbsjvdxo/Screenshot%202019-06-13%2011.07.44.png?dl=1)

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 13, 2019, 12:03

@schroedtert No I did not recompile jpscore, I'm really sorry this is all new to me. Now it should be recompiled, the branch is up to date. The result of the simulation is the same as befor.

@chraibi I hope this is the one you are looking for: ![Bildschirmfoto_2019-06-13_um_11.51.18](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/2781d11f8b4720e5fe05c0d8710ae76e/Bildschirmfoto_2019-06-13_um_11.51.18.png)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2019, 15:12

Tim, you are using the branch `develop`. 

Tobias works on the branch [287-waitingarea](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/tree/287-waitingarea)

So you need to 

- `git pull`
- `git checkout  287-waitingarea`
- then compile

Apart from that, it would be good to join our [Slack workspace](https://ias7.slack.com/) for quicker support. 
If you send me your Email-Adress I can invite you.

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jun 17, 2019, 11:13

@schroedtert Now I compiled correctly and tested 10 seeds. No more overlapping problem occurred. Thank you.  

Issue: WA max_peds exceeded by way problem

This is an addition to an issue above. WA_source distributes to WA_oben, WA_mitte and WA_unten; p = 0,7 / 0,2 / 0,1; max_peds = 10 / 20 / 40. 
When max_peds(10) of WA_oben is reached, no further peds are send from WA_source to WA_oben. But all peds who are already on their way to WA_oben continue and are not rerouting so they also enter WA_oben. The amount of waiting peds reaches 16. max_peds of the first WA (WA_source) is never exceeded by the number of peds heading for it and max_peds(WA_source) <= max_peds(WA_oben) is satisfied. So the mentioned conditions should be kept.

Folder with data: [https://1drv.ms/u/s!AsV6LgpLPxYhgbIMofWzPvfCzU8jLg?e=uWtQsq]


Issue: WA max_peds = min_peds 

I set max_ped = min_peds = „10“ in an other test to gain more control of the amount of peds. Sometimes fewer then min_peds are send to the next WA. This can be observed by around 115 seconds WA02 to WA20 (second duo from the bottom). Ped 35 should be going to WA20 but stays in WA02. This happens two times in a row. 

Folder with data: [https://1drv.ms/u/s!AsV6LgpLPxYhgbFp5EQTKgcEqgzKuA?e=auOneF]

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Jun 24, 2019, 13:07

@schroedtert 
Do the waiting areas work only with direction-strategies 10 or also with other?

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Jun 24, 2019, 13:10

At the moment only direction-strategy 10, but I’m not 100% sure, haven’t tested it with others for a while. The others may also work by ‘accident'.

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Jun 24, 2019, 13:13

Okay thank you, then I will check it.

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Jun 25, 2019, 16:54

mentioned in commit d0fb26a7112c32cf65d3c9bb2bf16234463e52d4

**Comment by anna-braun** [comment]
@schroedtert 
As discussed here is a file in which you can see that the WA does not distribute the agents evenly according to the probabilities: 
[Ausgabe.txt](https://github.com/JuPedSim/jpscore/files/3467237/Ausgabe.txt)

[Personen.xml.txt](https://github.com/JuPedSim/jpscore/files/3467235/Personen.xml.txt)
[Bahnsteig.xml.txt](https://github.com/JuPedSim/jpscore/files/3467226/Bahnsteig.xml.txt)
[events.xml.txt](https://github.com/JuPedSim/jpscore/files/3467230/events.xml.txt)
