### ISSUE TITLE
Schedule (for WAs)

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#372]
In Gitlab by @anna-braun on Feb 21, 2019, 13:22 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/306)]

For reopening the waiting areas we need a schedule:

**schedule.xml***    

```
<?xml version="1.0" encoding="UTF-8" ...?>
<JPScore project="JPS-Project" version="0.6" ...>

  <groups>
      <group id="1">
          <member wa_id="1"/>
          <member wa_id="2"/>
          <member wa_id="3"/>
      </group>
      <group id="2">
          <member wa_id="4"/>
          <member wa_id="5"/>
          <member wa_id="6"/>
      </group>
  </groups>

  <times>
      <time group_id="1">
           <t="60"/>
           <t="120"/>
           <t="350"/>
           <t="800"/>
      </time>

      <time group_id="2">
           <t="20"/>
           <t="80"/>
           <t="310"/>
           <t="760"/>
      <time/>
  </times>

</JPScore>
```

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Feb 21, 2019, 13:23

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 21, 2019, 17:17

assigned to @schroedtert

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Feb 22, 2019, 12:13

t is always the time a transition opens? If yes, how long it should stay open till it closes again?

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Feb 22, 2019, 12:22

Yes, t is the time when a transition opens.    
It should stay open until max_peds is reached or if a defined time is over.     
So the counter also has to be reset when closing the door.

**Comment by chraibi** [comment]
In Gitlab by @anna-braun on Mar 21, 2019, 11:39

Postponed until #294 is finished.

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Mar 30, 2019, 13:03

created branch [`306-schedule-for-was`](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/compare/develop...306-schedule-for-was) to address this issue

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on Mar 30, 2019, 14:46

Small changes, since #294 should work now, schedule will be processed as Events and hence opening doors. Also the closing time needs to be defined in the schedule file.

[schedule.xml](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/05e832774a82ae424e13f8a86888d53b/schedule.xml)

**Comment by chraibi** [comment]
In Gitlab by @123morgoth123 on Jul 1, 2019, 11:01

Schedules are not working with transitions which are mentioned in traffic_constraints.
(And two peds are just deleted while waiting in front of a closed door, number 9 and 12)

Files: [files](https://1drv.ms/u/s!AsV6LgpLPxYhgbJvUFWWlDPOjjCOqA?e=iD5S8o)

**Comment by schroedtert** [comment]
@anna-braun can this be closed?

**Comment by anna-braun** [comment]
Yes, it can be closed. There is already an other issue #539.
