### ISSUE TITLE
One-sided closed doors

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#378]
In Gitlab by @schroedtert on May 17, 2019, 08:56 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/320)]

Allows to pedestrian to go through in one direction but is (temp) closed from the other direction.

**Comment by chraibi** [comment]
In Gitlab by @schroedtert on May 19, 2019, 10:50

created branch [`320-one-sided-closed-doors`](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/compare/develop...320-one-sided-closed-doors) to address this issue

**Comment by zeroset** [comment]
@schroedtert what is about this issue? Are you still working on it?

**Comment by chraibi** [comment]
@zeroset is this issue really WIP?
 @schroedtert

**Comment by schroedtert** [comment]
It is still work in progress/almost finished. I need to test it some more.

**Comment by zeroset** [comment]
This was planned as workaround for waiting rooms without exit. Since this was a workaround and is no modeled in another way we close this issue and will not implement one sided doors at this moment.
