### ISSUE TITLE
inifile, header

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#380]
In Gitlab by @gjaeger on Jun 17, 2019, 10:48 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/325)]

The simulation *RiMEA_Test_04_0-5* does not run with `<header>` as described in the [documentation](http://www.jupedsim.org/jpscore/2016-11-01-inifile).

[ini_RiMEA_Test_04_0-5.xml](https://gitlab.version.fz-juelich.de/JuPedSim/jpscore/uploads/34bb482701018f085dfb6f803c49eeb1/ini_RiMEA_Test_04_0-5.xml)

[geo_RiMEA_Test_04.xml](/uploads/4fd1cb5dc22914899a3045e653a28593/geo_RiMEA_Test_04.xml)

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 18, 2019, 09:04

assigned to @xuqiancheng

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 18, 2019, 10:41

Maybe it's easier to change the documentation then to change `jpscore`.

*easier* because of the majority of demos and inifiles we've been using so far will have to be changed.

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Jun 18, 2019, 21:12

When was the structure changed? I like the typical structure of the ini-file as described in the documentation.

**Comment by chraibi** [comment]
In Gitlab by @xuqiancheng on Jun 19, 2019, 17:34

Solved by cc10c9ccf59fb25989eb25a2ffaee40b2fa6bff0

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Jun 24, 2019, 09:30

commit 4510345f0c1990a93c1e77314cdf86bde55decd3: Anything else? What about the Utests?

**Comment by chraibi** [comment]
@gjaeger  is this issue solved yet?

**Comment by gjaeger** [comment]
On GitHub, I can't find the branch _325_header_ from gitlab. There I changed the demo files. We haven't integrated the branch yet. 

@chraibi: You had made changes to this branch ( _325_header_) on gitlab. I can't find them. 

I am a bit confused.

**Comment by gjaeger** [comment]
closed after merge request #416

**Comment by gjaeger** [comment]
Based on the discussion in issue #448, I would like to ask the question whether we require the header? Or should we continue to allow both variants (with and without)?

**Comment by schroedtert** [comment]
We should also talk about about all the option which can be set in the ini-file, which are required, which are optional and what default values should be set if an option is missing and when the reading should be quit with an error message

**Comment by chraibi** [comment]
I would say, `header` should be necessary. 

If it is missing, `jpscore` should exit with error. 

@schroedtert you are right. See #455

**Comment by zeroset** [comment]
Closed and handled in #455
