### ISSUE TITLE
Writing Errors for WAs

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#382]
In Gitlab by @anna-braun on Jun 24, 2019, 13:03 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/330)]

In issue #327 we had to spend a lot of time to find our problem and in the end it was just one wrong letter in the definition of a waiting area. 
As we have mentioned in #327 the simulation failed, without writing an error to the log-file. In the huge files for KapaKrit we might have 3.000 lines or more. Finding a typing error without any message in the log-file could take hours.   
So, @schroedtert, is it possible to write such errors into the log? It does not have to be a very specified log-message, which tells you the specific line or something. But a small hint to see in which goal/waiting area the error occurs would be very helpful. Maybe by writing the goals id to the log.

**Comment by chraibi** [comment]
any updates here?

**Comment by schroedtert** [comment]
Closed with 7d5ed737646c0313760eb64de80f6b20fa5ace25
