### ISSUE TITLE
Unnecessary dependency on Boost/random

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#413]
Any special reason why in [Trips](https://github.com/JuPedSim/jpscore/blob/develop/geometry/Trips.cpp#L6) Boost is used to produce random numbers?

I think this functionality is standard in [C++11](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine) and should be used instead.

**Comment by schroedtert** [comment]
Closed with 7d5ed737646c0313760eb64de80f6b20fa5ace25
