### ISSUE TITLE
Warnings and code style in WaitingAreas

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#414]
It would be good to fix these warnings:

<img width="1225" alt="Screenshot 2019-07-17 11 47 59" src="https://user-images.githubusercontent.com/5772973/61345732-dd1a0780-a888-11e9-94bb-ed5a7942fb5a.png">

Besides, in the throughout the code, the convention of appending a `_` to member variables is used.  Therefore, it would be also good to stick to this convention in this [class](https://github.com/JuPedSim/jpscore/blob/develop/geometry/WaitingArea.h)

**Comment by schroedtert** [comment]
Closed with 7d5ed737646c0313760eb64de80f6b20fa5ace25
