### ISSUE TITLE
More general output

### ISSUE THREAD

**Issue by schroedtert** [JuPedSim/jpscore#418]
Proposal:
Instead of only writing one of the properties to the output file, write all available features as velocity, router, intermediate/final goal, to output file. With this the wanted property can be displayed in jpsvis without need to run a simulation multiple times when different properties are needed.

**Comment by chraibi** [comment]
Good idea. 
Maybe only for txt-files?

**Comment by gjaeger** [comment]
I suggest that we add the following properties: 
- velocity (vector quantity `v_x`, `v_y`, `v_z`)
- movement speed (scalar quantity `v`)

**Comment by gjaeger** [comment]
looks good (based on PR #483):
```
#V: speed of the pedestrian (in m/s)
#Vx: x component of the pedestrian's velocity
#Vy: y component of the pedestrian's velocity


#ID	FR	X	Y	Z	A	B	ANGLE	COLOR	V	Vx	Vy
1	0	0.85	5.09	0.00	0.21	0.21	0.00	0	0.00	0.00	0.00	
1	1	1.48	5.09	0.00	0.21	0.21	-0.00	255	1.30	1.30	-0.00	
1	2	2.13	5.09	0.00	0.21	0.21	-0.00	255	1.30	1.30	-0.00
```
