### ISSUE TITLE
Pedestrian Distribution

### ISSUE THREAD

**Issue by planospeedo** [JuPedSim/jpscore#420]
in function **_PossiblePositions_** from **_PedDistributor.cpp_**

`

    double bufx = 0.12;
    double bufy = 0.12;
    double amin = 0.18; // = GetAmin()->GetMean();
    double bmax = 0.25; // = GetBmax()->GetMean();
    double dx = amin + bufx;
    double dy = bmax + bufy;

`

With this, the distribution is hardcoded to dx = 0.3 m and dy = 0.37 m, which is a problem when using bigger pedestrian sizes and higher densities as overlapping initial distributions and no movement (at least when using the velocity model) occurs.

Example: pedestrian size is 0.4 m (l=0.2m)
First image: overlapping as amin=0.18

![Bildschirmfoto 2019-07-18 um 16 12 16](https://user-images.githubusercontent.com/15627872/61467368-c6081200-a97b-11e9-807e-5e680e5e2a28.png)

Second image: no overlapping when setting amin=0.25 for instance

![Bildschirmfoto 2019-07-18 um 16 13 13](https://user-images.githubusercontent.com/15627872/61467377-c86a6c00-a97b-11e9-95c1-049155508aca.png)

**Comment by gjaeger** [comment]
@planospeedo Should the values (in the code) only be increased? Or should they be dependent on the input?

**Comment by planospeedo** [comment]
@gjaeger input-dependent I suppose, otherwise it is for instance not possible to have high initial densities with smaller pedestrian sizes

**Comment by gjaeger** [comment]
OK. That would be my suggestion too.

**Comment by gjaeger** [comment]
The change was made at commit c30e7ad on Jul 4, 2014.

**Comment by gjaeger** [comment]
@planospeedo can wie close this issue?
