### ISSUE TITLE
Create pre-commit hook for clang-format

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#428]
- Use `travis` to automatically check the code formating of PRs.
- use [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
- maybe useful: build `.clang-format` [interactively](https://www.clangformat.com/)

**Comment by schroedtert** [comment]
We should also put the contribution guide to GitHub not only on JuPedSim.org and also add naming convention (camelcase, pascal case for all types).

**Comment by zeroset** [comment]
Hi @chraibi, i would prefer having clang-format as a pre-commit hook in git once we have clang format applied to the whole repository. This avoids unnecessary CI runs when format is wrong.

**Comment by chraibi** [comment]
Makes sense.

**Comment by Ozaq** [comment]
@zeroset I think this is done, right?

**Comment by zeroset** [comment]
thanks :)
