### ISSUE TITLE
Cmake Find OpenMP is port specific

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#445]
**JuPedSim - JPScore**

Branch `develop`. In the changes introduces in #440 

I think these lines here are port-specific:

```
        find_library(OpenMP_LIBRARY
            NAMES omp
            PATHS
                /opt/local
                /opt/local/lib/libomp
        )
        find_path(OpenMP_INCLUDE_DIR
            omp.h
            PATHS
                /opt/local
                /opt/local/include/libomp
        )
```

For `brew` openmp would be located in `/usr/local/Cellar/libomp/` instead.

**Comment by Ozaq** [comment]
@chraibi Only the paths you see are macport specific but they only work as additional search paths, CMake will still try to find the libs under the "normal" paths like `/usr/lib` or '/usr/include`. See https://cmake.org/cmake/help/v3.15/command/find_library.html for a full treatment on the search paths. The `find_library` / `find_path` calls are also used / necessary when using brew. The difference is that libomp when installed with brew is found in a default path.
