### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#456]
**JuPedSim - JPScore**

- Current date   : 06.08.2019
- Compiler       : cmake -DCMAKE_CXX_COMPILER=g++-9 ..
- Branch         : develop

Since yesterday I cannot compile jpscore.     
I tried it with "cmake .." and "cmake -DCMAKE_CXX_COMPILER=g++-9 .."       
If I compile with make it runs 100% but 2 errors occur and I cannot use jpscore:

![Bildschirmfoto 2019-08-06 um 12 54 12](https://user-images.githubusercontent.com/38530070/62534852-48347980-b84a-11e9-9b2f-7ea813c7c95a.png)

**Comment by Ozaq** [comment]
Hi @anna-braun to help diagnose the issue can you please do the following:

Create a new and empty build directory, cd to that directory and run `cmake .. ` without the explicit reference to use gcc9 and post the output.

**Comment by anna-braun** [comment]
@Ozaq 
We have solved the problem for me so I cannot reproduce the bug again. But I guess we found the problem as @planospeedo had produced the same error yesterday.      

1. OpenMP was not installed. -> Did not cause this error.
2. There was a problem with the "bin" directory. The filesystem could not be found. Before, this was located in the root directory ("jpscore/bin"), now it seems to be located in the build directory ("jpscore/build/bin"). After removing the old "bin" directory ("jpscore/bin") I could compile the code.

**Comment by Ozaq** [comment]
@anna-braun good to hear! I guess this can then be closed?

**Comment by planospeedo** [comment]
@Ozaq Normally when building, there would be a separate folder `bin` containing the executable. Now, this `bin` folder appears in the build directory. Was there a change in how the directories are arranged?

**Comment by Ozaq** [comment]
@planospeedo Yeah there was, all aoutput during build is now created in the build directory. This is commonly called an "out of tree" build. Since nothing is build into the source tree, you can now maintain multiple build direcories, e.g. one for Debug, Release, WITH_OPENMP=OFF etc...

**Comment by anna-braun** [comment]
> @anna-braun good to hear! I guess this can then be closed?

Yes it can be closed.
