### ISSUE TITLE
Geometry in traj-files

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#458]
In the trajectory files the geometry is saved with its path. If the files are moved to an other directory (e.g. Jureca -> Mac) or the directory is renamed, jpsvis cannot find the geometry files. As it is very uncomfortable to adapt all geometry paths we should change the trajectory files and jpsvis:
- Save the geometry without a path in the trajectory files(jpscore)
- Change jpsvis to read geometries from the same directory as the trajectory file.

**Comment by gjaeger** [comment]
*JPSvis* offers the possibility to load the geometry file separately (see [commit 9b496d47](9b496d47dda1f884c316ec3951be7975b11c4192) and discussion in #461).

**Comment by gjaeger** [comment]
@anna-braun Would you like to try this with _JPSvis_?

**Comment by anna-braun** [comment]
> _JPSvis_ offers the possibility to load the geometry file separately (see [commit 9b496d47](9b496d47dda1f884c316ec3951be7975b11c4192) and discussion in #461) 

> @anna-braun Would you like to try this with _JPSvis_?    
 
I tried it, but jpsvis collapses when I try to load both. Despite this, I think this is not very comfortable to load both. And before we changed the txt-files, it worked without a full path in the file, so this might need only a small change in the code @chraibi ?

**Comment by chraibi** [comment]
This is easily done if we have a consense. I see the point of moving simulation results from one system to another will be problematic, if absolute paths are used. 

Trajectory files are not always in the same directory as the geometry file. 

So what about having everything relative to the inifile?

**Comment by gjaeger** [comment]
> So what about having everything relative to the inifile?

We should avoid such lines in the header:
`#geometry: /Users/User/Documents/raw/../docu/geo_UNI_CORR_500_05.xml`

**Comment by chraibi** [comment]
Definitely, because of the absolute bath. 

So what I'm suggesting is this 

```
#geometry: ../docu/geo_UNI_CORR_500_05.xml
```
considering this structure
<img width="323" alt="Screenshot 2019-08-13 at 13 44 36" src="https://user-images.githubusercontent.com/5772973/62917917-b50ebd00-bdd0-11e9-9a27-06ed3aa03a3b.png">

**Comment by anna-braun** [comment]
> Definitely, because of the absolute path.
> 
> So what I'm suggesting is this
> 
> ```
> #geometry: ../docu/geo_UNI_CORR_500_05.xml
> ```
> 
> considering this structure
> <img alt="Screenshot 2019-08-13 at 13 44 36" width="323" src="https://user-images.githubusercontent.com/5772973/62917917-b50ebd00-bdd0-11e9-9a27-06ed3aa03a3b.png">

This is a good structure. And if you change it manually in the trajectory file it works already.

**Comment by zeroset** [comment]
Discussion is continued in #319
