### ISSUE TITLE
Changing the binary output dir to <build>/bin/ broke all tests based on "JPSRunTestDriver"

### ISSUE THREAD

**Issue by Ozaq** [JuPedSim/jpscore#461]
Ok this is my fault :/ JPSRunTestDriver does some path adjustment and assumes `jpscore` always to be in `<source>/bin/jpscore`. I foolishly thought the test might not run because of different reasons.

I am working on a patch, hope to have it available soon.

**Comment by gjaeger** [comment]
@Ozaq If you have an idea how we can simplify `JPSRunTestDriver`, this would be great. 

A good solution could also be helpful here ([JPSreport, issue 130](https://github.com/JuPedSim/jpsreport/issues/130)).

**Comment by Ozaq** [comment]
@gjaeger W.r.t. the path to `jpscore`, I would like to make this a test argument, which then can be set from CMake `add_test()`.

One thing that needs discussion are the output files. I would like to generate them into the current working directory or in a specified path, e.g. `jpscore --output-path=...`, but given my current understanding this would make it necessary to generate a relative path into the generated `trajectory.xml` files. Thus making it impossible to relocate them.

I would prefer if results where relocatable and possible to visualize w.o. the input data but this is not required to address this issue.

**Comment by gjaeger** [comment]
> One thing that needs discussion are the output files. I would like to generate them into the current working directory or in a specified path, e.g. jpscore --output-path=..., but given my current understanding this would make it necessary to generate a relative path into the generated trajectory.xml files. Thus making it impossible to relocate them.

That's a good idea.

**JPSvis** already offers the possibility to load a trajectory file without geometry. The geometry can then be selected separately. We can extend the routine so that the geometry can be loaded manually if the path is incorrect.
