### ISSUE TITLE
Documentation of the previous cmake modifications

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#465]
After the modifications of cmake (#421, #422, #435, #440, #446, #462 ), the documentation (e.g. [quick start](http://www.jupedsim.org/jpscore/2016-11-02-quickstart.html), [requirements](http://www.jupedsim.org/jpscore/2016-11-03-requirements.html)) would have to be revised and adapted (see also [comment](https://github.com/JuPedSim/jpscore/issues/456#issuecomment-519848814) in #456). 

Who would be able to do this?

**Comment by zeroset** [comment]
Will be done in #614
