### ISSUE TITLE
Geometry correction

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#467]
I have a geometry (station) with several external transitions (for train doors). When starting the simulation the geometry should automatically be corrected -> walls are cut to set transitions. @chraibi: In the result I could see, that there was a correction, but the corrected Geometry was not written to the directory. Does this have something to do with #300?

**Comment by chraibi** [comment]
No, I don't think this is related to #300 
Probably to other recent PR's the corrected geometry is not written. 

Would you please upload an example to reproduce this?

**Comment by anna-braun** [comment]
@chraibi 
here is the file: [BS-geo.zip](https://github.com/JuPedSim/jpscore/files/3495551/BS-geo.zip)

**Comment by chraibi** [comment]
@anna-braun with these files I did not have any problems. 
<img width="736" alt="Screenshot 2019-08-13 at 15 25 41" src="https://user-images.githubusercontent.com/5772973/62922707-a4654380-bdde-11e9-84c6-767c73bea548.png">
Maybe wrong file?

**Comment by anna-braun** [comment]
@chraibi I tried it right before I uploaded it here. The simulation works, thats not the problem, but the corrected file is not written.

Did you make any changes in the ini-file?

**Comment by chraibi** [comment]
Ok, simulation runs fine, but geometry still needs correction. I see the problem. 
Checking..

**Comment by chraibi** [comment]
Sorry I pushed this unintentionally in the main repo.
