### ISSUE TITLE
External files - missing "/" ?

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#468]
I wanted to use several external files in my ini-file. Therefore, I usually just have to write the filename:
![Bildschirmfoto 2019-08-09 um 14 43 51](https://user-images.githubusercontent.com/38530070/62779839-8d5be400-bab4-11e9-8a87-2a4322936cfc.png)

For the traffic file it works fine, the path is correct when just writing _..>06-traffic.xml<.._:
![Bildschirmfoto 2019-08-09 um 14 43 35](https://user-images.githubusercontent.com/38530070/62779837-8d5be400-bab4-11e9-9761-2ce4743ea406.png)

But for the event and schedule files there is a missing "/". If I just write _..>04-event.xml<.._ and _..>05-schedule.xml<.._, the path is wrong and the files cannot be found:
![Bildschirmfoto 2019-08-09 um 14 43 07](https://user-images.githubusercontent.com/38530070/62779836-8cc34d80-bab4-11e9-8b65-47ee1d3ac5a2.png)

You have to insert a "/" in front of the filename (_..>/05-schedule.xml<.._), then it works:
![Bildschirmfoto 2019-08-09 um 14 45 02](https://user-images.githubusercontent.com/38530070/62780320-baf55d00-bab5-11e9-9d16-f18518b029a4.png)

@Ozaq Did you maybe change this when cleaning the code or similar?     
How do we deal with it? Should I change the documentation accordingly, or can someone revert the changes so that all external file can be defined in the same way again?

**Comment by Ozaq** [comment]
@anna-braun Its definately a bug. I encountered it during the week. PR #460 should address this, although I didn't finish this yet since I ran into the random crash #464 and wanted to understand what happens there first.

**Comment by Ozaq** [comment]
@anna-braun This should now be fixed on develop with the recent merge of #460

**Comment by chraibi** [comment]
@anna-braun  reopen if necessary.
