### ISSUE TITLE
Distribution of agents

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#469]
For KapaKrit I have use geometry which has negative coordinates. I wanted to distribute agents in the "negative" area by using `x_min, x_max, y_min, y_max`, but it seems as it is not possible to use this function with negative values.

I also tried it with a simple example, but the result is the same:
`ERROR:	invalid bounds [0.00,-3.00,0.00,-5.00] of the group [1]. Max and Min values mismatched?`

[Raum_1_ini.xml.txt](https://github.com/JuPedSim/jpscore/files/3487988/Raum_1_ini.xml.txt)
[Raum_1.xml.txt](https://github.com/JuPedSim/jpscore/files/3487989/Raum_1.xml.txt)

**Comment by schroedtert** [comment]
It seems that you mixed up x_min/max. It should be x_min=-5 and x_max=0. Same goes for y-coordinates. Can you test it? We should add a test for the inputs.

**Comment by anna-braun** [comment]
> It seems that you mixed up x_min/max. It should be x_min=-5 and x_max=0. Same goes for y-coordinates. Can you test it? We should add a test for the inputs.

@schroedtert, I tested it. And for the small example it works now. For the KapaKrit station it still does not work:
`<group group_id="2020" agent_parameter_id="1" room_id="101" subroom_id="1" number="585" goal_id="-1" router_id="1"  x_min="17" x_max="20" y_min="-185" y_max="-10" pre_movement_mean="480"/>` 

![Bildschirmfoto 2019-08-12 um 09 28 41](https://user-images.githubusercontent.com/38530070/62850673-de9dea80-bce3-11e9-99fc-88ef8de638aa.png)

**Comment by chraibi** [comment]
@anna-braun  but this is another problem. 
Now, it seems to me that in the mentioned area, you can not distribute 585 agents.
(the maximum allowed of 5856 is misleading and refers to the whole subroom)

Why don't you check with a smaller number of peds and report back?

**Comment by anna-braun** [comment]
@chraibi the area is 525 m^2, so 585 agents should not be a problem, but I will check it with a smaller number of agents.
