### ISSUE TITLE
Intersection of obstacles with subroom

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#471]
**JuPedSim - JPScore**

Current date   : Aug 13 2019 08:14:37
Version        : 0.8.4
Commit hash    : v0.8.4-159-gbbe10374
Commit date    : Wed Aug 7 16:16:48 2019
Branch         : develop

**Describe the bug**
With [ini_UNI_CORR_500_05_om_3.xml.zip](https://github.com/JuPedSim/jpscore/files/3495565/ini_UNI_CORR_500_05_om_3.xml.zip) and [geo_UNI_CORR_500_05.xml.zip](https://github.com/JuPedSim/jpscore/files/3495574/geo_UNI_CORR_500_05.xml.zip), I get the following error message in the log file ([log_UNI_CORR_500_05_om_3.txt](https://github.com/JuPedSim/jpscore/files/3495581/log_UNI_CORR_500_05_om_3.txt)):

```
ERROR: 	the obstacle [0] intersects with subroom [0] in room [0]
     : 	the triangulation will not work.
ERROR: 	the obstacle [0] intersects with subroom [0] in room [0]
     : 	the triangulation will not work.
```

Two agents are stuck in the corners of the obstacles:
![traj_UNI_CORR_500_05_om_3_travisto_snap_190813_08h_0](https://user-images.githubusercontent.com/7759675/62920184-436d4980-bda5-11e9-85f7-8c5819922258.png)

Without the obstacles, all agents leave the room.

Any suggestions?

**Comment by chraibi** [comment]
I think that according to [this](http://www.jupedsim.org/jpscore/2016-11-02-geometry.html#obstacles)
<img width="738" alt="Screenshot 2019-08-13 at 14 53 27" src="https://user-images.githubusercontent.com/5772973/62921088-3cacf980-bdda-11e9-9886-972179068001.png">

Maybe you try to edit the obstacles and move them a bit?

**Comment by gjaeger** [comment]
"_should_" doesn't mean "_forbidden_". That's why I tried it. ;-) 

If I remove the obstacles, agents still get stuck in the corners.

![tmp_0000169](https://user-images.githubusercontent.com/7759675/62922119-e96f8280-bdaa-11e9-9ac3-5e77c3a61da8.png)

if I move the obstacles or the walls of the room a little bit ([geo_UNI_CORR_500_05.xml.zip](https://github.com/JuPedSim/jpscore/files/3495751/geo_UNI_CORR_500_05.xml.zip)), but nothing changes.

![traj_UNI_CORR_500_05_om_3_travisto_snap_190813_09h_0](https://user-images.githubusercontent.com/7759675/62922646-2e47e900-bdac-11e9-9e25-805a19565d42.png)

**Comment by chraibi** [comment]
You are using router [global_shortest](http://www.jupedsim.org/jpscore/2016-11-03-routing.html#global-shortest-path). This router needs convex subrooms/rooms. There is no need for adding helplines.

If you use `ff_global_shortest` with ` <exit_crossing_strategy>8</exit_crossing_strategy>`, then you should be able to evacuate them all.

**Comment by gjaeger** [comment]
> You are using router global_shortest. This router needs convex subrooms/rooms. This means you need to add helplines.

Interesting. When I use `ff_global_shortest` with `<exit_crossing_strategy>8</exit_crossing_strategy>`, I get the following message:
```
WARNING:	 Room [0] Subroom [0] is not convex!
        	 you might consider adding extra hlines in your routing.xml file
```

I'm getting 300 errors, like:
`ERROR: 	Could not find a route for pedestrian 229 in room 0 and subroom 0`

strange

**Comment by schroedtert** [comment]
> I'm getting 300 errors, like:
> `ERROR: Could not find a route for pedestrian 229 in room 0 and subroom 0`

This is due to the FF Router, nothing to worry about. When a ped leaves the building this message is generated, I’m working on removing this (see #374).

**Comment by chraibi** [comment]
@gjaeger close?

**Comment by gjaeger** [comment]
That would have been my suggestion now.
