### ISSUE TITLE
Project files organisation 

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#474]
**Is your feature request related to a problem? Please describe.**

`jpscore` needs many input files to start a simulation (at least two)

- [inifile](http://www.jupedsim.org/jpscore/2016-11-01-inifile) (required)
- [geomery](http://www.jupedsim.org/jpscore/2016-11-02-geometry) (required)
- [events](http://www.jupedsim.org/jpscore/2019-07-03-events) (optional)
- [scedule](http://www.jupedsim.org/jpscore/2019-07-03-schedule) (optional)
- [sources](http://www.jupedsim.org/jpscore/2019-04-12-sources) (optional)
- [goals](http://www.jupedsim.org/jpscore/2019-04-12-goals) (optional) 
- [traffic](http://www.jupedsim.org/jpscore/2019-04-12-traffic) (optional)
- [transitions](http://www.jupedsim.org/jpscore/2019-04-12-transitions) (optional)
- [routing global shortest](http://www.jupedsim.org/jpscore/2016-11-03-routing#global-shortest-path) (optional)
- [smoke factor](http://www.jupedsim.org/jpscore/2016-11-03-routing#ai-router) (optional)
- [train interface](http://www.jupedsim.org/jpscore/2019-06-19-trains.html) (optional)

After a successful simulation, many files are produced (at least one)

- [trajectories](http://www.jupedsim.org/jpscore/2016-11-03-trajectory) (always)
- `logfile` (**if** `<logfile>true</logfile>`) 
- `flow files` (**if** `<show_statistics>true</show_statistics>`)
- `vtk files` (**if** `<write_VTK_files>true</write_VTK_files>` is used with ff_router.

**Describe the solution you'd like**
In the old good days, the locations of these files used to be relative to the location of the inifile, since this one is *the project file*. 

Now, with an increasing number of files and the more output one generates, things get very messy very fast.

Therefore, I suggest a *fixed* structure like this one:

![Screenshot 2019-08-14 at 11 01 24](https://user-images.githubusercontent.com/5772973/62991647-ed6ed380-be82-11e9-9646-cc818f3243fa.png)

**Describe alternatives you've considered**
Alternatively, we can keep everything flat and simple like 
![Screenshot 2019-08-14 at 11 03 08](https://user-images.githubusercontent.com/5772973/62991683-1f803580-be83-11e9-96c9-5cc3bbb77fed.png)

Another alternative is to pass an argument as

```
jpscore inifile --output-path=dir
```

**Additional context**
Lately, we had issues with files and trajectories like in #460 #468 #448 

@Ozaq in #448 
> I am a big believer in "less is more" in cases as this, i.e. id rather be less flexible but easier to make robust. Reporting an error for absolute paths of output files sounds good to me, maybe even refuse any paths that are "escaping" the current working dir (i.e. "../"). Or being even more restrictive (simple to implement) and don't allow setting of any paths in the ini and allow --output-path as cmdline param that contains all output files. Last one being my favorite.

**Comment by gjaeger** [comment]
The list of the output files is to be extended by
- `vtk files` (if `<write_VTK_files>true</write_VTK_files>`)

**Comment by gjaeger** [comment]
I'm not a friend of a fixed structure. I'd like to continue to have the freedom to specify the folders of each output file in the ini-file.

I suggest we offer a fixed structure by default. We still retain the possibility of individual settings.

**Comment by schroedtert** [comment]
I’m in favour of a fixed structure, it allows us get more robust code. This is from my point of view the most important thing. I wouldn’t go for a default structure which can be changed by the user, it will cost us so much time we could better spent on more important things.

**Comment by gjaeger** [comment]
@schroedtert This causes me great problems with my existing structure. It's a big effort.

**Comment by schroedtert** [comment]
@gjaeger As you could see from previous issues, we already had some things, especially ‘..’ and ‘.’ uses which basically destroyed a lot, at the moment it seems that we have to handle individually for each OS and maybe each compiler... With the fixed structure you could write a script which moves the files in the structure you need.

**Comment by gjaeger** [comment]
@schroedtert A script would be a workaround for existing studies. I hadn't thought of that before.

**Comment by Ozaq** [comment]
@chraibi what is supposed to happen if you run the same simulation multiple times? With your proposal new results overwrite old results? Wouldn't it make sense to at least put them into a subfolder with a timestamp, e.g. `2019-08-18T181201`? That way the application can be run and by default will not overwrite older results.

**Comment by chraibi** [comment]
@Ozaq yes, you are right. Maybe also add the name of the inifile to the directory. 
Makes it easy to organize different projects (e.g. different inifiles) and many simulations (e.g. different seeds).

Here an update:
![Screenshot 2019-09-06 11 24 51](https://user-images.githubusercontent.com/5772973/64398917-291f4680-d099-11e9-9a1e-5b162f95f49c.png)

**Comment by zeroset** [comment]
I wold prefer having an output path as a command line argument. In this path i would create a directory with a date/time and put all files there. For consistency reasons i would additionally prefer to copy the complete geometry into the output files. Either into the trajectories itself or if the other files need the geometry as well as file into the output path. The problem with using the input geometry in the output data is that the geometry could change. With a copy of the geometry used for the certain simulation we would always have a consistent data.

**Comment by schroedtert** [comment]
Can this be closed? See #649
