### ISSUE TITLE
Rename configuration model parameter write_VTK_files to write_VTK_files_direction

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#484]
**JuPedSim - JPScore**

**Describe the bug**
The operational Model Tordeux2015 has a configuration parameter called `write_VTK_files`
```xml
<operational_models>
  <model operational_model_id="3" description="Tordeux2015">
    <model_parameters>
      <write_VTK_files>true</write_VTK_files>
    </model_parameters>
```
Unfortunately this parameter name is already used in FFRouters and is renamed internally to `write_VTK_files_direction`. To avoid ambiguity the configuration parameter should be renamed to `write_VTK_files_direction`. 

**Additional context**
See also #478 & #476

**Comment by chraibi** [comment]
@zeroset  can you document this option please? 
Here is the [right place](https://github.com/JuPedSim/jpscore/blob/gh-pages/_posts/2016-11-01-operativ.md).

**Comment by Ozaq** [comment]
Writing of vtk output has been removed.
