### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#491]
For more reliable development we need to put Testcases and Demos together for continuous Testing for PRs and nightly testing. This should be done with juelich tests, rimea tests and existing demos. In the future we should extend those test with checks on statistics of the results. 
For convenience we should group the tests by execution time so that we are able to run small, medium and large testsuites. The testsuite itself will be written in python. 

For collecting the testcases and other documentation there is a [wiki page](https://github.com/JuPedSim/jpscore/wiki/integration_testing).

- [ ] Collect existing tests and demos
- [ ] Fix broken test
- [ ] Check existing python script for test execution
- [ ] Unify test execution

**Comment by schroedtert** [comment]
I tested the demos for the #472, following demos are not working at the moment:
- scenario_5_ship: there seems to be an error with the geometry, which may be related to our geometry correction function.
- scenario_5_events: either the events are not working properly or our routing also considers closed doors. We may have to check whether beds leave room only through open doors.
- scenario_12_waiting_areas: router ff_trips is deleted ( I am on it to change it, #472 needs to be merged first)
- scenario_13_schedule: same as scenario_12

Other question, why are we not using consecutive numbering for the demos? Are there some demos missing in our repo? Also we have scenario_5_ twice ...
