### ISSUE TITLE
Print Backtrace on error

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#498]
For better Debugging I want to have a backtrace after a segmentation fault or other error. Unfortunately it is not very easy to have this in a portable way. That is why we start with implementing this for specific platforms and compilers only. Please try to find a library which works on several platforms. 

ACs: 
- Backtrace for Linux gcc
- Backtrace for Linux clang
- Backtrace for MacOS clang

**Comment by schroedtert** [comment]
Haven’t look in detail in it, but boost offers a stack trace library which seems to be header only and maybe also platform and compiler independent. http://boostorg.github.io/stacktrace/index.html

**Comment by zeroset** [comment]
Ticket closed and reopened when we have a good solutions for this.
