### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#506]
- Update instructions in the readme-file

Here it could be mentioned, that there is a script `setup-deps.sh` that can be run before to help with the installation.

- Sync with online documentation 

﻿﻿﻿ http://www.jupedsim.org/jpscore/2016-11-02-quickstart.html

Basically, this wiki page should contain the same information as in the readme file or it can be removed.

**Comment by schroedtert** [comment]
Should we use the website or move the documentation entirely to the GitHub wiki pages? Only using the wiki may be easier for users, as they could find all the information here in the repo.

**Comment by gjaeger** [comment]
The GitHub wiki pages are sorted alphabetically. To structure the Wiki individually you can create one sidebar. A detailed structure is currently not possible. By default, we could place a table of contents after the heading on the page. Let's try it out.

Sources: https://guides.github.com/features/wikis/

**Comment by Ozaq** [comment]
I don't mind either but I have to admit that the gh-pages for jpscore look very well done. I am not sure if they can be done as pretty with the gh-wiki.
I also like the point @schroedtert raises that it would be nice to keep the doc next to the sources. I just recently saw that Github now allows to have gh-pages content in the master branch in a sub folder called docs. See their doc for that: https://pages.github.com/

I just tried if that works: https://pages.github.com/ (not yet synced, gh takes some time but it should be readable 20min from now on) and the corresponding repo:
https://github.com/Ozaq/doctest

This would allow to stay with your fancy theme, keep the doc close to the source AND allow doc changes to be a normal part of a PR. One drawback is that it cannot be configured from which branch the doc is created, it has to be master.

**Comment by zeroset** [comment]
I fully agree with @Ozaq, maybe we should think about moveing everything into the master branch and have a doc folder. I want to avoid the work necessary to migrate everything to the wiki. At the end gh-pages is propably much more powerful as well.
