### ISSUE TITLE
Door status

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#533]
As discussed yesterday, here is the issue about the door statuses and its functions.

The following three door statuses exist:
* _open_
* _close_
* _temp_close_     

They can all be set and changed by an event. Additionally _temp_close_ is used for the door-flow regulation and for max_agents, which causes some problems.

So here is a solution approach.
* Events have priority before the door-flow regulation.
* When max_agents are reached the door status is _close_.
* Doors which are closed by max_agents can be opened again by the event "reset".
* If the door status is _temp_close_ the agents should wait in front of the door until it opens again.
* If a door status is _close_, the agents should look for an other door and **not** wait in front of the closed door. And if there is no other open door, the agents should wait inside the room and the simulation should **not** crash.

![Door_status](https://user-images.githubusercontent.com/38530070/68376869-a9b9fc00-0149-11ea-94aa-4900e5b79532.png)

**Comment by schroedtert** [comment]
One question:
> Doors which are closed by max_agents can be opened again by the event "reset”.

What should happen if OPEN is used as event? Nothing?

**Comment by anna-braun** [comment]
> One question:
> 
> > Doors which are closed by max_agents can be opened again by the event "reset”.
> 
> What should happen if OPEN is used as event? Nothing?

Correct.

**Comment by schroedtert** [comment]
@anna-braun If all doors in a room are closed, what should the pedestrians do?
- standing at their current position
- waiting
- move to last goal and maybe stand in front of a closed door
- anything else?

**Comment by anna-braun** [comment]
> @anna-braun @chraibi If all doors in a room are closed, what should the pedestrians do?
> 
> * standing at their current position
> * waiting
> * move to last goal and maybe stand in front of a closed door
> * anything else?

@schroedtert 
I would say, if all doors are closed, the agents should wait in the room next to their final gaol. E.g. for stations, if there are no train doors, they should go to the platform and wait there, if possible.

**Comment by schroedtert** [comment]
Closed with #561.
