### ISSUE TITLE
Missing goal file in trajectory

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#540]
I did a simulation with external files, which worked fine, but the goal file was not correctly written to the trajectory file. It only says "file", it should be "goals.xml".     
#goals: /Users/anna/Desktop/**/jpscore/53-06-sources/20191108/**file**
       
And when I typed the name manually, the goals were still not shown when using jpsvis.

My version is from 31.10.2019

[Archiv.zip](https://github.com/JuPedSim/jpscore/files/3824671/Archiv.zip)

**Comment by chraibi** [comment]
> And when I typed the name manually, the goals were still not shown when using jpsvis.

I'll look at the jpsvis problem in another PR.
