### ISSUE TITLE
Handling Logged Errors

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#560]
Currently we do not have a unified error handling at all. It would be nice to stop the program after an Error was logged. We could think about adding `std::abort` to the `Logging::Error` function. This would at least go sure that the application is stopped on error. Non-critical errors must be changed to warning. @chraibi @schroedtert @Ozaq Any opinion? It is not meant as error handling, more safety feature to stop execution on Error.

**Comment by schroedtert** [comment]
I like the idea. But first we have to check if we are consistent with out `Logging::Error` calls. I think we have some “Errors” reported, which are more warnings than real errors.

For example, reports an error when no file is given, even if no events are desired:

```
    Logging::Info("Parsing event file");
    TiXmlDocument docEvent(eventfile.string());
    if(!docEvent.LoadFile()) {
        Logging::Error(fmt::format(check_fmt("Cannot parse event file: {}"), 
            docEvent.ErrorDesc()));
        return false;
    }
```

**Comment by Ozaq** [comment]
@zeroset Oh well... this pretty much depends on the underlying reason the call to Logging::Error was done.

I see at least two reasons:
1.) There was a programming error, e.g. an unexpected enum value, a dynamic cast going wrong. This is a big fat bug and should call `Logging::Error` and `std::abort` directly

2.) There was unexpected input, e.g. an unknown model name, broken geometry etc... anything that is "wrong" input but can be given to the program at runtime. In this case `Logging::Error` is fine but calling std::abort is not. The application should as graceful as possible exit (std::exit is probably even to heavy handed but MIGHT be ok). The error message NEEDS TO BE HELPFUL! 

In the end I think each and every call to Logging::Error has to be evaluated and input validation liberally applied to the code.
