### ISSUE TITLE
FF Router FindExit depends on exit strategy

### ISSUE THREAD

**Issue by schroedtert** [JuPedSim/jpscore#562]
**Describe the bug**
The FFRouter returns different values depending on the exit strategy. With 8 it returns the next transition ignoring crossings in between. Leading to errors in the door statistics, as the ped is always too far and thus gets counted multiple times.
Interface of Router seems not be strict enough, needs refactoring.

**Expected behavior**
Choice of next goal should be independent from exit_strategy and always be the closest crossing/transition.

**Additional context**
Originally from #556.
[router-interface.zip](https://github.com/JuPedSim/jpscore/files/3863852/router-interface.zip)

**Comment by zeroset** [comment]
see #663

**Comment by Ozaq** [comment]
FF-Router is removed for v0.10
