### ISSUE TITLE
Static route assignement

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#57]
In Gitlab by @chraibi on Nov 3, 2014, 13:11 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/42)]

Define a static route (escape route) pedestrians should follow.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone

**Comment by zeroset** [comment]
@chraibi Is this still a desired feature? Shouldn't it be part of an existing router? Should this be a new router?

**Comment by chraibi** [comment]
@schroedtert implemented this somehow. Maybe he can update us all.
