### ISSUE TITLE
FF-Router move to door closest to desired exit

### ISSUE THREAD

**Issue by schroedtert** [JuPedSim/jpscore#570]
At the moment the FF-Router sends the peds only to their desired exit if all doors between current position and exit are open/temp_close. When one door on the way is closed, the peds wait in their current room instead of progressing to closed door.

Current situation: (green=open door, red=closed door)
![Picture1](https://user-images.githubusercontent.com/15690524/69809605-5be56080-11ea-11ea-9adb-e7f4f19ef1cc.png)

Should situation:
![Picture12png](https://user-images.githubusercontent.com/15690524/69809651-6f90c700-11ea-11ea-88bd-8c1e6ee2eb36.png)

**Comment by zeroset** [comment]
@schroedtert still valid?

**Comment by Ozaq** [comment]
FF-Router is removed for v0.10
