### ISSUE TITLE
Clean up cmake file 

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#574]
`jpscore`'s build process got some lifting and [cleanup](https://github.com/JuPedSim/jpscore/pull/440). 

`jpsreport` needs the same treatment as well.

**Comment by Ozaq** [comment]
@chraibi & @zeroset & @gjaeger I think this can be closed after integrating report into jpscore

**Comment by Ozaq** [comment]
err.... I had a look into the file this DEFINITELY needs cleanup :P. Ill open a PR :/
