### ISSUE TITLE
Add test FD

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#583]
In Gitlab by @chraibi on Nov 10, 2014, 17:02 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/11)]

Compare the FD of jpsreport with a reference result file.

**Comment by gjaeger** [comment]
In handling this issue, we should take into account the discussion of issue #613.

**Comment by chraibi** [comment]
@gjaeger any progress here?

**Comment by gjaeger** [comment]
@chraibi yes
