### ISSUE TITLE
Sources - Wrong times for frequency 

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#595]
I tested an other function for the sources. I have 5 sources which have the same frequency, but different start times (time_min). So I would expect, that the sources start generating agents at time_min and the next time is time_min+frequency. But what happens its, that each source starts at time_min and then generates the agents with a "global" frequency, so there is no difference between the times when agents are created from different sources. You can see it on the picture. "Soll" = what is expected, "ist" = what happens in the simulation.

![Bild](https://user-images.githubusercontent.com/38530070/70632258-c062df80-1c2e-11ea-9e1e-909a4613d4aa.png)
Here are the files: [Archiv.zip](https://github.com/JuPedSim/jpscore/files/3950980/Archiv.zip)

- [x] Fix Bug
- [x] Create Tests to detect this bug in the future

**Comment by chraibi** [comment]
It seems to me that there is a misunderstanding in the functionality of sources.

According to the documentation: 

```
frequency: time in seconds of generation of pedestrians (default = 1).
```

For source 0 (in the figure), this means: From 5 to 60 create agents every 8 seconds; in other words at 8, 16, 24, 32, 40, 48, and 56. 
(these are exactly the crosses in the figure above).

In the [code](https://github.com/JuPedSim/jpscore/blob/master/libcore/src/pedestrian/AgentsSourcesManager.cpp#L100) you can see the following conditions:

```
bool inTime      = (current_time >= srcLifeSpan[0]) && (current_time <= srcLifeSpan[1]);
```
and 

```
bool newCycle = std::fmod(current_time, src->GetFrequency()) == 0;
```

- `inTime` makes sure the actual time is between min and max times of the source (-> the source is activated) 

- `newCycle`: when the source is *activated* we start generating agents every multiple of *frequency*.

Having said that, I think there is some debug in the code, see the circles in the following figure. 
It seems that at the beginning the sources are somehow laggy...

![595](https://user-images.githubusercontent.com/5772973/71633825-03edaf80-2c17-11ea-8c53-8c993193c7b0.png)

**Comment by chraibi** [comment]
After PR #637

![595](https://user-images.githubusercontent.com/5772973/71635195-ab241400-2c22-11ea-8bf1-8c8f340c5f18.png)

**Comment by anna-braun** [comment]
I tested it with pr 637 and it works as I expect it, thanks!
