### ISSUE TITLE
New release 0.9 is pending

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#632]
Since, the code encountered several major changes, regarding structure and functionality, I suggest releasing a new version 0.9.

Things to be considered are 

- [ ] Change version from `0.8.4` to `0.9` in all cmake files
- [ ] Create a `tag`
- [ ] Upload executables to Release-Page
- [ ] Write a release summary (like a changelog)
- [ ] Update documentation where necessary

**Comment by zeroset** [comment]
@chraibi can you describe the issue more detailed please?

**Comment by chraibi** [comment]
description updated.

**Comment by gjaeger** [comment]
Does a hard-coded version number in the cmake files make sense? Isn't the git-tag-commit statement enough?

**Comment by chraibi** [comment]
Yes, you have a point. 
```
"${GIT_EXECUTABLE}" describe --tags --abbrev=0
```
gets us the version from the tag (assuming we are disciplined enough to stick to a certain naming of tags).

If there no other hidden tricks, this solution sounds good to me too.
