### ISSUE TITLE
Tutorials in jpsreport and jpscore

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#633]
It would be nice to have the new tutorials as jupyter notebooks too. 

Things to cover might be:

  1. editing jpscore inifile
  2. creating geometry
  3. making jpscore simulation
  4. editing jpsreport inifile
  5. analysis
  6. plot results. Voila!

**Comment by zeroset** [comment]
@chraibi How and why do you want to have jupyter notebooks?

**Comment by chraibi** [comment]
How: 
Like this one 
https://github.com/JuPedSim/jpscore/blob/master/jpsreport/demos/HowTo.ipynb

Why: Jupyter notebook is self-contained and can be run along with explanations. It does not have to be a notebook.
