### ISSUE TITLE
Check all jpscore demo files

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#635]
`jpscore` has many demo scenarios. 

We need to make sure they work seemingly with the `master`
 branch.

## How to proceed (suggestion)

- [x] Rename the demos as follows "%2d_description"  and `description` as is now. For example:  "01_corridor"

- [x] Create a README.md for every demo following the following [template](https://gist.github.com/chraibi/b99049e331fe60ada413eb41fd8e4517).

- [x] Report (and eventually fix) demos that are not working. 
- [x] tick below the finished demos. 
## Demos 

- [x] scenario_1_corridor
- [x] scenario_2_bottleneck
- [x] scenario_3_corner
- [x] scenario_4_stairs
- [x] scenario_5_events
- [x] scenario_5_ship
- [x] scenario_7_floorfield
 - [x] scenario_10_big_room
- [x] scenario_11_sources
- [x] scenario_12_waiting_area
- [x] scenario_13_schedule

**Comment by xuqiancheng** [comment]
- [ ] **Demo 06_ship** doesn't work. The output is [output_06_ship.txt](https://github.com/JuPedSim/jpscore/files/4086151/output_06_ship.txt)

- [ ] **Demo 07_floorfield** works well, but the corrected geometry is not in the demo folder.

- [ ] **Demo 08_big_room** works well, but the door statistics is not in the demo folder and the result is wrong.

- [ ] **Demos 10_sources** works well, but I didn't find the definition of *strategy 11* in the [document](http://www.jupedsim.org/jpscore_direction.html)

**Comment by chraibi** [comment]
@xuqiancheng did you make all the necessary changes? Can your PR be reviewed?

**Comment by xuqiancheng** [comment]
> @xuqiancheng did you make all the necessary changes? Can your PR be reviewed?

I have made some changes to rename the demos and create README.md for each demos.
And I fix some small problems I found to make demos work well.

But the problems I mentioned in https://github.com/JuPedSim/jpscore/issues/635#issuecomment-576262057 haven't been solved yet.  So I haven't make a PR yet.

Should I fix these problem or we need discussion?

**Comment by chraibi** [comment]
>     * [ ]  **Demo 06_ship** doesn't work. The output is [output_06_ship.txt](https://github.com/JuPedSim/jpscore/files/4086151/output_06_ship.txt)

I would remove this demo, unless you can fix the geometry with some effort.

>     * [ ]  **Demo 07_floorfield** works well, but the corrected geometry is not in the demo folder.

Can you use a *correct* geometry?

>     * [ ]  **Demo 08_big_room** works well, but the door statistics is not in the demo folder and the result is wrong.

Why is the result wrong?

>     * [ ]  **Demos 10_sources** works well, but I didn't find the definition of _strategy 11_ in the [document](http://www.jupedsim.org/jpscore_direction.html)

use the strategy we have for the ff-router.

**Comment by xuqiancheng** [comment]
> Why is the result wrong?

`2020-01-30 15:17:34.947] [info] Exit ID [0] used by [80] pedestrians. Last passing time [44.58] s
[2020-01-30 15:17:34.947] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_0_big_room_250_traj.txt
[2020-01-30 15:17:34.947] [info] Exit ID [1] used by [46] pedestrians. Last passing time [37.46] s
[2020-01-30 15:17:34.947] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_1_big_room_250_traj.txt
[2020-01-30 15:17:34.948] [info] Exit ID [2] used by [53] pedestrians. Last passing time [42.54] s
[2020-01-30 15:17:34.948] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_2_big_room_250_traj.txt
[2020-01-30 15:17:34.948] [info] Exit ID [3] used by [121] pedestrians. Last passing time [46.21] s
[2020-01-30 15:17:34.948] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_3_big_room_250_traj.txt
`

@chraibi 
When we run big_room_250_ini.xml, actually there are 250 pedestrians evacuate from the room. But from the result of door statistics there are 300 pedestrians evacuate from the room.

**Comment by chraibi** [comment]
please keep only the small version of the inifile. I checked, that it is 300, it's correct.

**Comment by chraibi** [comment]
Please also add documentation of the demos with screenshots. 
I suggest adding a file in `docs/pages/jpscore` called `jpscore_demos.md`, like [test](http://www.jupedsim.org/jpscore_tests_juelich.html)

but for every bullet add a screenshot of the simulation.
