### ISSUE TITLE
Option to write logging information to log file

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#644]
issue #459 _Setting a log file location removes errors from output to stdout_ was closed because with the logging rework no log file can be set anymore.

The possibility to write the logging-information into a (log-)file would be good. Can we implement this option again?

**Comment by zeroset** [comment]
We should introduce a named command line parameter setting the name of the log file. The log file should be written into the new introduced output folder (see #649)

**Comment by chraibi** [comment]
`--log logfile`

**Comment by gjaeger** [comment]
Hasn't this issue already been solved for _jpsreport_ with the [procedure](https://www.jupedsim.org/jpsreport_inifile.html#logfile) described in the manual? [Here](https://www.jupedsim.org/jpsreport_introduction.html#run-jpsreport) one could add the described procedure for _jpsreport_. Whereby this is a duplication. Perhaps one refers to the existing description

Can this option also be used with jpscore? If so, we should adapt the [manual](https://www.jupedsim.org/jpscore_introduction.html)?
