### ISSUE TITLE
The door statistics are wrong

### ISSUE THREAD

**Issue by xuqiancheng** [JuPedSim/jpscore#663]
When I run demo 08_big_room. I found the door statistics is wong.

In the inifile, there are 250 pedestrians evacuating from four exits. 

![image](https://user-images.githubusercontent.com/32732507/73537828-b937a100-4429-11ea-8213-b774048c1e1a.png)

But in the door statistics, there are 300 pedestrians evacuating from the four exits.

`2020-01-30 15:17:34.947] [info] Exit ID [0] used by [80] pedestrians. Last passing time [44.58] s [2020-01-30 15:17:34.947] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_0_big_room_250_traj.txt [2020-01-30 15:17:34.947] [info] Exit ID [1] used by [46] pedestrians. Last passing time [37.46] s [2020-01-30 15:17:34.947] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_1_big_room_250_traj.txt [2020-01-30 15:17:34.948] [info] Exit ID [2] used by [53] pedestrians. Last passing time [42.54] s [2020-01-30 15:17:34.948] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_2_big_room_250_traj.txt [2020-01-30 15:17:34.948] [info] Exit ID [3] used by [121] pedestrians. Last passing time [46.21] s [2020-01-30 15:17:34.948] [info] More Information in the file: /home/qiancheng/workspace/jpscore_develop/jpscore/build/bin/results/flow_exit_id_3_big_room_250_traj.txt`

**Comment by chraibi** [comment]
Are the statistics still wrong?

@xuqiancheng 
@schroedtert

**Comment by schroedtert** [comment]
Statistics are better, but not 100% correct.
Due to #762 some pedestrians are considered as still on the exit even they are not, thus breaking the counting.

**Comment by xuqiancheng** [comment]
For the demo 07_big_room, the statistics are correct now.

**Comment by chraibi** [comment]
Okay, then we can close this issue.
