### ISSUE TITLE
Test generated Binaries/Setup scripts

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#687]
Set up Teamcity to create the install packages automatically AND setup a package installation test that works along this line:

- Download the package
- install the package
- run the application with a minimal sample
- uninstall the application

**Comment by zeroset** [comment]
We are now able to automatically generate Packages using CPack. We need a way to automatically test the resulting packages on Windows and MacOS. At the moment this is open for discussion.

**Comment by Ozaq** [comment]
Windows / MacOS packages are build. Automatic testing of the created packages is too time consuming at the moment.
