### ISSUE TITLE
Integration of jpsreport in jpscore

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#688]
Although `jpsreport` is already integrated into `jpscore`, some functionalities are still missing. 

Things to be done:

1. Extensive testing of the methods and integration of the tests in cmake (also assigned to epic issue #720)
   - Method A (issue #695 solved by PR #668)
   - Method B - open issue #690
   - Method C - open issue #691
   - Method D (issue #692 solved by PR #753)
   - Method I (issue #697 solved by PR #763)
   - Method J (issue #696 solved by PR #768)
 
2. Logging functionality should be changed à la `jpscore`.
- issue #788 (solved by PR #791 )

3. Geometry functionalities in `jpsreport` should use `jpscorelib`
- issue #708

**Comment by gjaeger** [comment]
@chraibi You forgot method J.

**Comment by chraibi** [comment]
Thanks. Could you open the corresponding issue?
(.. and for method A too, please)

**Comment by gjaeger** [comment]
done (see #695 and #696)

**Comment by chraibi** [comment]
> What about the last two items?
>     1. Logging functionality should be changed à la `jpscore`.

Still has to be done. Feel free to submit a PR.

**Comment by gjaeger** [comment]
> Still has to be done. Feel free to submit a PR.

Is PR #790 a suggestion for item 3?

**Comment by chraibi** [comment]
PR #790 is for item 2.

**Comment by gjaeger** [comment]
> PR #790 is for item 2.

Sorry, I meant item 2. I changed it.
