### ISSUE TITLE
Use Jinja in tests

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#689]
In the tests, we use a self-made [script](https://github.com/JuPedSim/jpscore/blob/master/systemtest/makeini.py) to generate inifiles out of a "master inifile".

The script reads in the master-inifile values, which may be lists or arrays of len>1 and generates in return many inifiles composed of the cartesian product of these lists.

For example for the following input
```
 {'num_threads': [5, 1, 2], 'tmax': [1, 2]}
```

the script generates:

``` [
    {'num_threads': 5, 'tmax': 1}, {'num_threads': 5, 'tmax': 2},
    {'num_threads': 1, 'tmax': 1}, {'num_threads': 1, 'tmax': 2},
    {'num_threads': 2, 'tmax': 1}, {'num_threads': 2, 'tmax': 2}
    ]
```

In this issue, the possibility of replacing this functionality with the [jinja](https://jinja.palletsprojects.com/en/2.11.x/templates/#variables) should be considered and eventually implemented.

Suggestion: [gist](https://gist.github.com/chraibi/0e7e4a358528bb72c4f3b3a8aee6c229)

**Comment by Ozaq** [comment]
Done
