### ISSUE TITLE
Remove hard-coded periodic from VelocityModel

### ISSUE THREAD

**Issue by schroedtert** [JuPedSim/jpscore#723]
Currently in the VelocityModel the values for the periodic area are hard coded, which should be removed. 
`VelocityMode.cpp:39ff`:
```
double xRight = 26.0;
double xLeft  = 0.0;
double cutoff = 2.0;
```

Afterwards it needs to be discussed if we still need this option, as it is not used GFCM and VelocityModel.

**Comment by chraibi** [comment]
I think we need this option, but it should be implemented in a more general way.

**Comment by Ozaq** [comment]
Support for periodic geometry has been removed.
