### ISSUE TITLE
Incomplete cmake command in documentation

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#724]
CMake prefix path `-DCMAKE_PREFIX_PATH=$(pwd)/deps` is missing in documentation of "How to build" on Linux

**Comment by Ozaq** [comment]
@JetteSchumann I just saw this popup, if you update this you could also link to the cmake doc describing the details of this flag since its not JPS specific but a general configuration option of cmake.
https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html
