### ISSUE TITLE
Inconsistent definition of points for geometry and measurement area

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#747]
When testing Method D I had an issue with the definition of the mearuement area.

I defined walls in the geometry file as follows:
```xml
<polygon caption="wall">
<vertex px="10.0" py="0.0"/>
<vertex px="-0.5" py="0.0"/>
<vertex px="-0.5" py="6.0"/>
<vertex px="10.0" py="6.0"/>
</polygon>
```

Based on that I created a measurement area in the jpsreport ini file:
```xml
<area_B id="1" type="BoundingBox" zPos="None">
<vertex px="4.0" py="0.0"/>
<vertex px="4.0" py="6.0"/>
<vertex px="8.0" py="6.0"/>
<vertex px="8.0" py="0.0"/>
</area_B>
```

After running jpsreport the logging says "INFO:	Success with Method D using measurement area id 1!" - which is not correct. All output data are nan.

Thanks to @gjaeger I found out that the measurement area defintion must be:
```xml
<area_B id="1" type="BoundingBox" zPos="None">
<vertex x="4.0" y="0.0"/>
<vertex x="4.0" y="6.0"/>
<vertex x="8.0" y="6.0"/>
<vertex x="8.0" y="0.0"/>
</area_B>
```

This is quite irritating. We should have consistent naming here and the input error is not detected. This problem should occur whenever a (faulty) box-mearsurement area is used, not Method D only.

Does anyone know where the "p" comes from? Is it standing for "point"?
Should we use `px` when defining `area_B` and `area_L`?

**Comment by gjaeger** [comment]
> Does anyone know where the "p" comes from? Is it standing for "point"?

"p" stands for "point".
