### ISSUE TITLE
Bug: IsLineSegment depends on line length

### ISSUE THREAD

**Issue by schroedtert** [JuPedSim/jpscore#762]
It seems to be an accuracy issue when checking if a point depends to a line segment. 

Point (4.00036, 0)

Test 1:
Line (4, -1.5) - (4, 1.5) -> Point is not in line segment, as they are not colinear (`std::abs(crossProduct) > J_EPS` see below)

Test 2:
Line (4, -0.4) - (4, -0.4) -> Point is in line segment

```cpp
// From Macros.h
#define J_EPS 0.001        //0.001

// From Line.cpp
/*
 *  Prüft, ob Punkt p im Liniensegment enthalten ist
 * algorithm from:
 * http://stackoverflow.com/questions/328107/how-can-you-determine-a-point-is-between-two-other-points-on-a-line-segment
 *
 */
bool Line::IsInLineSegment(const Point & p) const
{
    Point differenceTwoAndOne = _point2 - _point1;
    Point differencePAndOne   = p - _point1;

    // cross product to check if point i colinear
    auto crossProduct = differenceTwoAndOne.CrossProduct(differencePAndOne);
    if(std::abs(crossProduct) > J_EPS)
        return false;

    // dotproduct and distSquared to check if point is in segment and not just in line
    double dotp = differencePAndOne.ScalarProduct(differenceTwoAndOne);

    if(dotp < 0.) {
        return false;
    }

    if(dotp > (differenceTwoAndOne).NormSquare()) {
        return false;
    }
    return true;
}
```

Suggestion for discussion:
- decrease J_EPS
- use `boost::geometry::distance()` with a threshold
- use 'boost::geometry::within()` with a certain threshold polygon
- use other algorithm

**Comment by chraibi** [comment]
Can you write a self-contained example to debug this function?

**Comment by chraibi** [comment]
@schroedtert

**Comment by schroedtert** [comment]
Sorry for the late reply.
Just add this to LineTest.cpp. `isIn` and `isIn2` should both return the same value as the distance to the line is the same.

```cpp
TEST_CASE("Bug", "[Bug][Line]")
{
    Point point{4.00026, 0.};

    Line shortLine{{4., -0.4}, {4., 0.4}};
    bool isInShort = shortLine.IsInLineSegment(point); // returns true
    
    Line longLine{{4., -1.95}, {4., 1.95}};
    bool isInLong = longLine.IsInLineSegment(point); // returns false
}
```
If you increase the length of longLine the value returned stays false (Tested with `Line longLine{{4., -5.}, {4., 5.}}`).

**Comment by chraibi** [comment]
> Suggestion for discussion:
> 
>     * decrease J_EPS
> 
>     * use `boost::geometry::distance()` with a threshold
> 
>     * use 'boost::geometry::within()` with a certain threshold polygon
> 
>     * use other algorithm


It looks like a precision error. The calculation for a (very) long line or a (very) short line is not the same. Therefore, I'm not really sure using another library will solve this problem.

For this exact case, I get the following error for `shortLine`
1.689999821197218921e-07

and for `LongLine`
3.4666666426375059018e-08

Now, depending on the tolerance threshold we still could get a false or a true for one of the lines.

**Comment by schroedtert** [comment]
My experience:
1. decrease J_EPS: will lead to failing unit tests (no further investigation)
2. at the moment my favorite
3. Can not be used as: 
> boost::geometry::within will return false for points that are exactly on the border of a geometry object, which will be the case for all points in a line. You need to change the strategy to permit within to return true for points that are on the border. (from https://stackoverflow.com/a/52613876)

**Comment by chraibi** [comment]
> will return false for points that are exactly on the border of a geometry object,

*exactly*? I mean floating point arithmetic..

**Comment by schroedtert** [comment]
See: https://stackoverflow.com/a/52627475
It seems that boost::geometry::distance with a threshold is the suggested way to deal with this.
