### ISSUE TITLE
Build tests

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#783]
According to the documentation in the [readme](https://github.com/jupedsim/jpscore#build_testing-defaults-to-off
) 

There are two cmake parameters. First, `BUILD_CPPUNIT_TEST` to activate the unit tests and 

`BUILD_TESTING` to **"Build full system tests "**

What is the meaning of full system tests here? I was confused at first and thought it means **all** tests. 

What is the difference between these two parameters?

**Comment by schroedtert** [comment]
`BUILD_CPPUNIT_TEST`: Build catch2 unit tests, can be executed via `make unittests`
`BUILD_TESTING`: Builds all test in systemtest, can be executed via `ctest`
