### ISSUE TITLE
XML Schema, Error reading Attributes

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#807]
Some jpscore and jpsreport ini files contain different information about the XML schema, like

[jpscore/demos/01_corridor/corridor_ini.xml](https://github.com/JuPedSim/jpscore/blob/master/demos/01_corridor/corridor_ini.xml)
```xml
<?xml version="1.0" encoding="UTF-8" ?>

<JuPedSim project="JPS-Project" version="0.7"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```
[jpsreport/demos/bottleneck/ini_AO_300.xml](https://github.com/JuPedSim/jpscore/blob/master/jpsreport/demos/bottleneck/ini_AO_300.xml)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<JPSreport project="AO_300" version="0.8.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

Earlier versions contained additional elements and enabled validation (based on an old pdf-documentation):
```xml
<?xml version=" 1.0" encoding="UTF-8" ?>

<JPSreport project="JPS-Project" version="0.8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/JuPedSim/jpsreport/blob/develop/xsd/jps_report.xsd">
```

Due to a typo I got the following error message when starting a simulation with jpscore:

```bash
[2020-06-29 09:54:50.831] [info] Loading and parsing the project file <inifile.xml>
[2020-06-29 09:54:50.833] [error] Error reading Attributes.
[2020-06-29 09:54:50.833] [error] Exception in IniFileParser::Parse thrown, what: Could not parse the project file
```
The error message is not very helpful for searching and correcting. 

In an earlier version I got the information in which attribute the error is located. This would be very helpful for the future application. What are the options to localize the reason for the error?

**Comment by chraibi** [comment]
I think we decided at some point not to stop using xsd-schemes since we don't have any easy way to programmatically use them to verify XML files. 
(@schroedtert right?)

I know that these XML-error messages are not easy to decipher, but maybe two solutions could help mitigate
 this problem: 

1. Use an online validator [for example](https://xmlvalidation.com/)
2. Use a good Editor like for example Emacs :-) 

<img width="1068" alt="Screenshot 2020-07-21 12 21 14" src="https://user-images.githubusercontent.com/5772973/88042776-c74eba80-cb4c-11ea-89d3-7f4eb3f0aa71.png">

**Comment by schroedtert** [comment]
> I think we decided at some point to stop using xsd-schemes since we don't have any easy way to programmatically use them to verify XML files.
Yes, we decided to not put any work into these as they had already diverged quite a lot from the actutal parsed input. And I'm not sure if the xsd file would work in such cases, I would also propose to use any text editor (atom, notepad++, ...) that can properly deal with xml files.

**Comment by gjaeger** [comment]
@chraibi @schroedtert Thank you for your comments. From my side, I propose to close the issue. There are no further activities planned/desired.

**Comment by chraibi** [comment]
For future reference #436
