### ISSUE TITLE
Integrate Method I into Method D

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/jpscore#808]
With the introduction of the new parameter `use_blind_points` and `calc_IFD_only` we can compute method I in method D

- [x] Add mentioned parameters to Method D
- [x] Adopt tests of method I to run as Method D with corresponding parameters 
- [x] Check and adopt existing inifiles in repository

**Comment by JetteSchumann** [comment]
According to [this](https://github.com/JuPedSim/jpscore/issues/792#issuecomment-660098447) I will integrate the functionalities of Method I as followed:
 ```xml
<method_D enabled="true">
   <global_individual enabled="true"/>
   <blind_points enabled="true"/>
</measurement_method_voronoi>
```

- `global_individual' is `false` by default. If it's `true` IFD data are calculated for the whole geometry. No measurement area needs to be defined.
- `blind_points`is `true`by default and enables a voronoi cell calculation when less than 4 people are in the MA.
