### ISSUE TITLE
operational models: model parameters

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#813]
**JuPedSim - JPScore**

- Version        : 0.8.4
- Commit hash    : v0.8.4-991-g9749a79
- Branch         : master

**Describe the bug**

With this setting

```xml
  <model operational_model_id="1" description="gcfm">
    <model_parameters>
      <solver>euler</solver>
      <stepsize>0.01</stepsize>
      <exit_crossing_strategy>3</exit_crossing_strategy>
      <linkedcells enabled="true" cell_size="2.2"/>
      <force_ped  nu="0.1"
                  dist_max="2"
                  disteff_max="3"
                  interpolation_width="0.1"/>
      <force_wall nu="0.2"
                  dist_max="3"
                  disteff_max="2"
                  interpolation_width="0.1"/>
    </model_parameters>
```

I get the following error message:

```bash
[...] [error] The linked-cell size [2.2] should be larger than the force range [3.0]
[...] [error] Could not start simulation. Check the log for prior errors
```

In my opinion, this problem occurs because the value for the parameter `disteff_max` is larger than the `cell_size` for the parameter `linkedcells`. 

**Expected behavior**
In my opinion, a model-specific parameter should override a general parameter. If `disteff_max` is larger than the `cell_size`, then the value of `disteff_max` should be used for the `cell_size`.

**Comment by chraibi** [comment]
The idea here is that for long-ranged forces, more neighbors need to be considered. 

This restriction is to ensure, that when using LC-neighbors, no other agents are left, although they may be influential.

I prefer not to implicitly override these parameters.

**Comment by gjaeger** [comment]
> The idea here is that for long-ranged forces, more neighbors need to be considered.

Which parameter do you mean by _long-ranged forces_? Do you mean `nu` (strength of the force), `dist_max` (maximum force at contact) or `disteff_max` (cut-off-radius)?

> I prefer not to implicitly override these parameters.

How can we extend the manual? Any suggestions?

**Comment by gjaeger** [comment]
After a talk with @chraibi, when applying the parameters `disteff_max` and `cell_size`, it is important to note that they are related. `disteff_max` may not be greater than `cell_size`, otherwise `cell_size` must be adjusted by the user.

This is illustrated in the following sketch by @chraibi 

<img width="425" alt="sketch" src="https://user-images.githubusercontent.com/7759675/88069883-56ba9480-cb72-11ea-8d32-81bc3085c92b.png">
