### ISSUE TITLE
Installation under Linux

### ISSUE THREAD

**Issue by mirakuepper** [JuPedSim/jpscore#854]
During the installation of jpscore using Linux Mint 19 Tara I had some issues with `cmake`. The same problem previously occured with Ubuntu 18.04 LTS. 

`cmake` was not able to find any working compilers. I solved the problem with including `-DCMAKE_CXX_COMPILER=„g++-8“` after every single `cmake`. 

However this is not only needed in all commands in terminal, but as well the script `scripts/setup-deps.sh` needed to be manually adapted. When I included the line `-DCMAKE_CXX_COMPILER=„g++-8` after every single `cmake`, it worked just fine.

Not sure if this problem only occures with my Linux installation, but maybe this will help others stumbling across the same problem.

**Comment by Ozaq** [comment]
I will close this as we do not provide support for Ubuntu LTS releases, only for latest Ubuntu.
