### ISSUE TITLE
Provide a tool to merge trajectory files

### ISSUE THREAD

**Issue by Ozaq** [JuPedSim/jpscore#883]
The current release of jpscore (0.8.4) writes trajectories in ~16Mb chunks. The next release of jpsvis (0.9) will be able to load much larger trajectory files (>1GB) without issues. Because of this jpscore no longer needs to write trajectories into multiple output files. On the current master jpscore already no longer splits trajectory files.

To allow users with simulations created with jpscore 0.8.4 to benefit from jpsvis new capabilities, we need to provide a command line tool to merge existing chunks into a single trajectory file.

Constraints:
* The tool should be self documenting, i.e. all command line options / help shall provide helpful text so that no further online documentation needs to be visited.
* There shall be no gaps in frame indices, i.e. if the lowest frame index is 6 and the highest is 10, then 7,8,9 need to be part of the input.
* The tool needs to check that the FPS entry in the trajectory file matches in all input files
* The tool needs to check that the associated geometry path is identical

Recommendations:
* Use python argparse for command line handling https://docs.python.org/3/library/argparse.html
* Use a file based merge-sort approach to operate on the input files

Example use:
`jps --output trajectories.txt --input traj_1.txt traj_2.txt traj_3.txt`

**Comment by chraibi** [comment]
[Example](https://fz-juelich.sciebo.de/s/lyZ9eBbMQ4M0tgB)

**Comment by Ozaq** [comment]
@ChristianHirt The following is a minimal example what `jpsvis` is expecting

```txt
#framerate: 8.00
#geometry: stairs_geo.xml
1	0	1.00	0.50	0.00	0.18	0.25	180.00	0	
2	0	4.00	2.50	0.00	0.18	0.25	180.00	0	
3	0	2.00	0.50	0.00	0.18	0.25	180.00	0
...
```

So for your check if all input files are from the same run I recommend to only compare the `#framerate` and `#geometry` lines in the input files.
