### ISSUE TITLE
Provide a tool to convert PedTrack trajectories to JuPedSim compatible format

### ISSUE THREAD

**Issue by Ozaq** [JuPedSim/jpscore#927]
Trajectories written by PedTrack currently cannot be read by JpsVis. 

The differences in format are:

1.) Framerate tag

JuPedSim uses `#framerate: <double>
PedTrack uses `# framerate: <double> fps`

2.) Ordering
JuPedSim trajectory data needs to be ordered by frame
PedTrack trajectory is ordered by pedestrian id

3.) Available data
JuPedSim requires a shape (Ellipsis) to render a Pedestrian and a optional orientation is desired
PedTrack data does not contain this information

To be able to effectively compare simulation data with experimental data it would be very beneficial to display PedTrack data in JpsVis. For this use case we would like to have a command line tool that creates a JpsVis compatible trajectory file from a PedTrack trajectory file that also correctly embeds the path to the respective geometry file.

An invocation should look something like this:
```
jpsconvert --geometry geo.xml --trajectory pedtrack_trajectory.txt > trajectory.txt
```

**Comment by chraibi** [comment]
Can be closed, I think

**Comment by Ozaq** [comment]
This has been implemented.
