### ISSUE TITLE
Add vcpkg.json (or update README)

### ISSUE THREAD

**Issue by ChristianHirt** [JuPedSim/jpscore#928]
**Is your feature request related to a problem? Please describe.**
Compilation of the project is needlessly complicated on Windows right now. This could be made easier by adding a vcpkg.json. This could also be used on the other platforms to make sure the same version of the dependencies is used across platforms and to make JPSVis independent of system package managers.

**Describe the solution you'd like**
Addition of a vcpkg.json

**Describe alternatives you've considered**
Update the README, e.g. get rid of qt in vcpkg-install and add glm as dependecy

**Additional context**
This vcpkg.json worked locally for me (on vcpkg from last monday):
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "jpsvis",
  "version": "0.8.2",
  "dependencies": [
  {
	"name": "vtk",
	"features": [
		"qt",
		"opengl"
	]
  },
  "glm"
  ],
  "builtin-baseline": "699c8779f1b0feb4ed3564716d1ed31f69663ea6"
}
```

(This was written by Deniz Kilic;)

**Comment by Ozaq** [comment]
Done.
