### ISSUE TITLE
Unintended door warning

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#962]
I checked the warnings of this simulation example (version 0.9.3):
[UnintendedDoor.zip](https://github.com/JuPedSim/jpscore/files/8176129/UnintendedDoor.zip)

`[2022-03-03 09:12:59.390] [warning] Ped 134: used an unindented door 10, but wanted to go to 9.` 

This warning makes no sense (apart from the typo :wink:). The agent is moving straight from one door to the next one.

**Comment by schroedtert** [comment]
Played a bit around, when using boost::geometry to detect the intersection the warnings don't appear anymore. Not tested if all functionality is as before, especially the overlap detection:
```cpp

**Comment by Ozaq** [comment]
Thanks a lot for looking into it, I agree this looks like a bug in the current implementation.

**Comment by Ozaq** [comment]
Fixed on master and for 0.9.5
